= Hazelcast Cloud Documentation
// Settings:
ifdef::env-github[]
:warning-caption: :warning:
endif::[]
// URLs:
:url-org: https://github.com/hazelcast
:url-contribute: https://github.com/hazelcast/hazelcast-docs/blob/develop/.github/CONTRIBUTING.adoc
:url-ui: {url-org}/hazelcast-docs-ui
:url-playbook: {url-org}/hazelcast-docs
:url-staging: https://develop--nifty-wozniak-71a44b.netlify.app/home/index.html

This repository contains the Antora components for the Hazelcast Cloud documentation.

The documentation source files are marked up with AsciiDoc.

== Docs Structure

This section describes some important information about how this repository is structured:

- The component name, version, and start page are configured in each branch's `antora.yml` file.
- The navigation for all modules is stored in the ROOT module's `nav.adoc` file.
- The {url-playbook}[docs site playbook] instructs Antora to automatically build the site using content in the `master` branch as well as any tags that are prefixed with *v*.

== GitHub Actions

To automate some elements of the build process, this repository includes the following GitHub Actions:

.GitHub Actions
[cols="m,a,a"]
|===
|File |Description |Triggers

|validate-site.yml
|Validates that all internal and external links are working
|On a pull request to the `main` branch

|build-site.yml
|Builds the production documentation site by sending a build hook to Netlify (the hosting platform that we use)
|On a push to the `main` branch
|===

== Contributing

If you want to add a change or contribute new content, see our {url-contribute}[contributing guide].

To let us know about something that you'd like us to change, consider {url-org}/hazelcast-reference-manual/issues/new[creating an issue].
