== Add Payment Method
:description: {hazelcast-cloud} Standard Edition admin users are prompted to add payment details after signing in for the first time. Adding your payment details sets up automatic payments based on your usage. You cannot create clusters until you have added a payment card.

{description}

NOTE: {hazelcast-cloud} Trial Edition users do not need to add payment details. The payment details for {hazelcast-cloud} Dedicated Edition users are agreed and set up as part of account creation.

To add your payment details, complete the following steps:

. Sign in to the link:{page-cloud-console}[{hazelcast-cloud} console,window=_blank].
. Select *Account* from the side navigation bar
. Select *Organization* from the *Account* options
+
The Info screen displays.

. Select the *Billing & Payments* tab
+
The Billing & Payment screen displays.

. Select *Add Payment Method*
+
The Add Payment Method screen displays.
+
NOTE: Currently, card payments are the only supported payment method.

. Complete the Add Payment Method form as follows:
+
.. Enter the full name of the organization in the *Full Name / Company* text box
.. Enter the first line of your address in the *Address Line 1* text box
.. Optionally, add the second line of your address in the *Address Line 2 (Optional)* text box
.. Enter your country in the *Country* text box
.. Enter the city used in your address in the *City* text box
.. Enter your post, or zip, code in the *Postal Code* text box
.. Enter the long number from your payment card in the *Card Number* text number
.. Enter the date from the Expires End section of your card in the *Expiration Date* text box
.. Enter the card verification code on the reverse of your card in the *CVC* text box

. Select the *ADD PAYMENT DETAILS* button to save your payment details. Selecting the *Cancel* button returns you to the Billing & Payments screen without saving your payment details

NOTE: Hazelcast uses a third party to store payment details and process payments. Payment details are not stored in Hazelcast.

You can add only one payment method to your account. You can xref:update-payment-method.adoc[update your payment details] at any time.
