= Backing up and Restoring a Cluster
:description: You can create a backup of all your cluster data and later restore new clusters from that backup.

{description}

NOTE: Hazelcast Dedicated clusters create a backup automatically once every 24 hours.

To back up or restore clusters in a team, you must have either an admin or developer role. See xref:teams-and-users.adoc[].

== Creating a Backups

. Go to *Manage Cluster* > *Backup And Restore*.
 
. Click *Create a Snapshot*.

The time of creating a backup can vary according to the size of your cluster and the data. You need to wait until the backup status is *Ready* before using it for restore.

You can keep at most 10 backups. The oldest backup will be deleted automatically after the 10th backup.

== Restore a New Cluster from a Backup

Once you have at least one backup, you can easily use it to bootstrap a new cluster by clicking the *Restore* button of the backup you selected. Then, you need to follow nearly the same process as you followed while creating your cluster to create a new cluster with the backup.

Once you click the *Restore Data to New Cluster* button, It will create a new cluster with the data your backup has. 

IMPORTANT: Do not delete the cluster that owns the backup until the new cluster is running.
