= Backing up and Restoring Data
:description: You can create a backup of your cluster data and later restore new clusters from that backup.

{description}

// tag::cluster-data[]
Cluster data includes the following:

- Configuration settings
- Cluster-side modules
- Jobs
- Map and JCache data structures
// end::cluster-data[]

Serverless clusters create a backup automatically once every 24 hours and when they are stopped.

To back up or restore clusters in a team, you must have either an admin or developer role. See xref:teams-and-users.adoc[].

== Creating a Backups

. Go to *Manage Cluster* > *Backup And Restore*.
 
. Click *Create a Snapshot*.

The time it takes to create a backup can vary, according to the size of your cluster and the amount of data in it.

You can keep at most 10 backups. The oldest backup will be deleted automatically after the 10th backup.

== Restore a New Cluster from a Backup

Once you have at least one backup, you can easily use it to bootstrap a new cluster by clicking the *Restore* button of the backup you selected. Then, you need to follow nearly the same process as you followed while creating your cluster to create a new cluster with the backup.

Once you click the *Restore Data to New Cluster* button, It will create a new cluster with the data your backup has. 

IMPORTANT: Do not delete the cluster that owns the backup until the new cluster is running.
