= Backing up and Restoring Data
:description: You can create a backup of your data on a production cluster and later restore new clusters from that backup.
:cloud-tags: Manage Clusters
:cloud-order: 56

{description}

include::partial$cluster-data.adoc[]

{hazelcast-cloud} Serverless production clusters create a backup automatically once every 24 hours, and when they are xref:stop-and-resume.adoc#pausing-a-cluster[paused].

== Creating a Backup

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank] and select your cluster.

. Go to *Manage* > *Backups*.
 
. Click *Create Manual Backup*.

The time it takes to create a backup can vary, according to the size of your cluster and the amount of data in it.

You can keep at most 10 backups. The oldest backup will be deleted automatically after the 10th backup.

== Restoring a New Cluster from a Backup

When you have at least one backup, you can use it to bootstrap a new cluster. The new cluster is created using the xref:release-notes.adoc[current Hazelcast version].

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank] and select your cluster.

. Go to *Manage* > *Backups*.

. Click *Create Manual Backup*.

. Click *Restore* in the row of your selected backup.

. When the details of your new cluster are displayed, you can update its cluster name.

. Click *Restore Data to a New Cluster* to deploy your new cluster. To check the Hazelcast version of the new cluster after it is created, go to the dashboard and view the *Cluster Details*.

IMPORTANT: Do not delete the cluster that owns the backup until the new cluster is running.
