= Backing up and Restoring Data
:description: You can create a backup of your cluster data and later restore new clusters from that backup.
:cloud-tags: Manage Clusters
:cloud-order: 56

{description}

include::partial$cluster-data.adoc[]

{hazelcast-cloud} Serverless clusters create a backup automatically once every 24 hours and when they are xref:stop-and-resume.adoc#pausing-a-cluster[paused].

To back up or restore clusters in a team, you must have either an admin or developer role. See xref:teams-and-users.adoc[].

== Creating a Backup

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank] and select your cluster.

. Click *Create a backup*.
 
. Click *Create Manual Backup*.

The time it takes to create a backup can vary, according to the size of your cluster and the amount of data in it.

You can keep at most 10 backups. The oldest backup will be deleted automatically after the 10th backup.

== Restoring a New Cluster from a Backup

When you have at least one backup, you can use it to bootstrap a new cluster.

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank] and select your cluster.

. Click *Create a backup*.

. Click *Restore* in the row of your selected backup.

IMPORTANT: Do not delete the cluster that owns the backup until the new cluster is running.
