= Charts and Statistics
:description: You can monitor the performance metrics and status of your clusters, using the console.

{description}

To monitor a cluster:

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank] and select your cluster.
. Below the *Cluster details* section, charts are grouped into two sections:

** *Cluster metrics*: Charts for both cluster and client metrics.
** *Map metrics*: Charts for monitoring maps.

+
Charts are updated every 5 seconds. When you hover your mouse cursor onto any chart area, you can see the related value corresponding to the cursor's location.

NOTE: Metrics may not represent the current state of the cluster. The displayed metrics are sometimes 5-10 seconds older than the current state of the cluster because of the latency between the cluster reporting the metrics and the charts reading and displaying them.

== Cluster Metrics

In the *Cluster Metrics* section, you can see the following charts.

=== Cluster Memory Chart

This chart shows your cluster's memory capacity (`Cluster Max Memory`, the blue line) and the size of currently used memory (`Cluster Used Memory`, the green line). As the green line approaches the blue line, you should think about scaling out. Note that `Cluster Used Memory` is the total amount of memory used for both primary and backup entries. 

=== Client Count Chart

This chart shows the number of clients that are connected to your cluster. 

== Map Metrics

Below the Cluster Metrics, you see the *Map Metrics* where the charts specific to maps are displayed. You can select the map that you want to monitor from the drop down just under the Map Metrics heading. 

In the *Map Metrics* part of the Cluster Details page, you can see the charts described in the below sections.

=== Map Used Memory Chart

This chart shows how many megabytes of data are being used by this map. The value is the total memory of both primary and backup entries. For example, if you have put 100 entries with 1 KB of size each and if your map's backup count is 1, then the value of `Map Used Memory` should be 200 KB. 

=== Average Latency Chart

This chart shows the average latency values (in milliseconds) for the get, put, and remove operations.

=== Throughput Chart

This chart shows the total number of get, put, and remove operations executed by the cluster per second.

=== Entry Count Chart

This chart shows the count of entries in the map. This count does not include the backup entries. So, it provides the same count as the `map.size()` API.

=== Hit Ratio Chart

This chart shows the number of get operations that return a value, divided by the total number of all get operations.

=== Read/Write Ratio Chart

This chart shows the total number of get operations, divided by the total number of put operations at any time.

== Client Statistics

Below the Map Metrics, you see the *Client Statistics*. It shows the list of clients connected to your cluster.

Each client name in this list includes a unique ID that is automatically generated by the client. You can see the client details by clicking on any client's name.

=== Client Details

When you click on a client's name, you will see a panel that provides detailed information about the client.