= Creating a {hazelcast-cloud} Standard Cluster
:description: You can create a cluster for development or production.
:page-aliases: create-starter-cluster.adoc, starter-clusters.adoc, create-standard-cluster.adoc, availability-zones.adoc, instance-types.adoc
:cloud-tags: Manage Clusters
:cloud-title: Creating Standard Clusters
:cloud-order: 51

{description}

== Before you Begin

You need a xref:create-account.adoc[{hazelcast-cloud} account].

To create a cluster, you must add a xref:payment-methods.adoc[payment card] to your account.

== Using the {hazelcast-cloud} Console

[tabs] 
====
Development cluster:: 
+ 
--
To create a development cluster, do the following:

// tag::development[]
. Sign into the link:{page-cloud-console}[{hazelcast-cloud} console,window=_blank].
. Click *Create New Cluster*.
. Click *Create Cluster*.
. Select *Development*.
. Update the cluster name if you want to. You cannot change the cluster name after the cluster is created.
. Click *Start Development Cluster*. 
. Wait while your cluster is created. When the cluster is up and running, a *Quick Connection Guide* is displayed with instructions for connecting a sample client to it.
// end::development[]
--
NOTE: Development clusters are xref:stop-and-resume.adoc#pausing-a-cluster[paused] automatically when you don't connect to the cluster for 24 hours. 

Production cluster:: 
+ 
--
To create a production cluster, do the following:

// tag::production[]
. Sign into the link:{page-cloud-console}[{hazelcast-cloud} console, window=blank].
. Click *Create New Cluster*.
. Click *Create Cluster*.
. Click *Production*.
. Update the cluster name if you want to. You cannot change the cluster name after the cluster is created.
. Click *Start Production Cluster*
. Wait while your cluster is created. When the cluster is up and running, a *Quick Connection Guide* is displayed with instructions for connecting a sample client to it.
// end::production[]
--
NOTE: Production clusters are xref:stop-and-resume.adoc#pausing-a-cluster[paused] automatically if you don't have a payment method set up _and_ you don't connect to your cluster for 24 hours. 
====

== Next Steps

Try the xref:get-started.adoc[hello world tutorial].

Explore all xref:tutorials.adoc[tutorials].

