= Create an Account
:description: You must create an account before you can use {hazelcast-cloud}. Creating an account creates an organization with a single user. You can sign up using an email address and password, or with a Google or GitHub account.
:toclevels: 3

{description}

Whichever sign-up method you use, you are given the choice of creating a free Trial account, or a paid Viridian Standard account. For further information on the available {hazelcast-cloud} editions, see the xref:overview.adoc[Hazelcast {hazelcast-cloud}] section.

NOTE: By creating an account, you are agreeing to the {hazelcast-cloud} link:https://viridian.hazelcast.com/terms-of-service[Terms of Service,window=_blank] and the Hazelcast link:https://hazelcast.com/privacy/[Privacy Policy,window=_blank]. These documents are also vailable from the sign-up page.  

To create an account, complete the following steps:

. Open the link:{page-cloud-signup}[{hazelcast-cloud} sign-up page, window=_blank]

. Enter the sign-up information for the method you prefer, as follows:
+
[tabs] 
====
Email::
+ 
--
. Enter your name in the *Full Name* text box
. Enter your email address in the *Email* text box
. Enter the password you want to use when signing in in the *Password* text box
. Select the *Create Account* button
+
A confirmation email is sent to the provided email address.

. Select the *Verify your email* link in the confirmation email to confirm your account
. Sign into your account using the credentials you entered during sign up
--
Google:: 
+ 
--
NOTE: If you use this method, you do not create a {hazelcast-cloud} password. If you subsequently want to sign in with your email and use MFA in {hazelcast-cloud}, you must set a password first. For further information on setting a password, see the xref:change-password.adoc[] topic.

. Select the *Google* button
. Select the Google account you want to use, or create a Google account
+
If you are not already signed in to your Google account, sign in now.
+
If you have enabled MFA on your Google account, you must confirm your identity using your usual method.

A confirmation email is sent to your registered email address and the {hazelcast-cloud} console displays the Cluster screen ready for you to continue. 
--
GitHub:: 
+ 
--
NOTE: If you use this method, you do not create a {hazelcast-cloud} password. If you subsequently want to sign in with your email and use MFA in {hazelcast-cloud}, you must set a password first. For further information on setting a password, see the xref:change-password.adoc[] topic.

. Select the *GitHub* button
+
If you are not already signed in to your GitHub account, sign in now.
+
If you have enabled MFA on your GitHub account, you must confirm your identity using your usual method.

. Select the *Authorize Hazelcast* button

A confirmation email is sent to your registered email address and the {hazelcast-cloud} console displays the Cluster screen ready for you to continue.
--
====

Depending on the method you chose, you might be asked for further information. This can include the following:

* Why you are using {hazelcast-cloud}
* Your role
* Your organization name
* Your location
* Your payment information

== Next Steps

Follow the xref:get-started.adoc[Hello World] tutorial.

Alternatively, finish setting up your organization as follows:

* xref:add-users.adoc[Add users] to the organization
* Set up a xref:payment-methods.adoc[payment method or budget tracker]
* Enable xref:multi-factor-authentication.adoc[MFA]
