= Creating a {hazelcast-cloud} Serverless Cluster
:description: You can create a free cluster for development or production.
:page-aliases: create-starter-cluster.adoc, starter-clusters.adoc, create-standard-cluster.adoc, availability-zones.adoc, instance-types.adoc
:page-serverless: true
:cloud-tags: Manage Clusters
:cloud-title: Creating Serverless Clusters
:cloud-order: 51

{description}

== Before you Begin

You need a xref:create-account.adoc[Hazelcast {hazelcast-cloud} account].

To create more than one cluster, you must add a xref:payment-methods.adoc[payment card] to your account.

== Using the Hazelcast {hazelcast-cloud} Console

[tabs] 
====
Development cluster:: 
+ 
--
To create a development cluster, do the following:

// tag::development[]
. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Click *Create New Cluster*.
. Click *Create Development Cluster*.
. Update the cluster name if you want to. You cannot change the cluster name after the cluster is created.
. Click *Create Cluster*. 
. Wait while your cluster is created. When the cluster is up and running, a *Quick Connection Guide* is displayed with instructions for connecting a sample client to it.
// end::development[]
--

Production cluster:: 
+ 
--
To create a production cluster, do the following:

// tag::production[]
. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console, window=blank].
. Click *Create New Cluster*.
. Click *Create Production Cluster*.
. Update the cluster name if you want to. You cannot change the cluster name after the cluster is created.
. Click *Create Cluster*
. Wait while your cluster is created. When the cluster is up and running, a *Quick Connection Guide* is displayed with instructions for connecting a sample client to it.
// end::production[]
--
====

[NOTE]
====
Development and production clusters are xref:stop-and-resume.adoc#pausing-a-cluster[paused] when both of these conditions are true:

- You don't connect to the cluster for 24 hours.
- You don't have a payment method set up for your Hazelcast {hazelcast-cloud} account.
====

== Next Steps

Try the xref:get-started.adoc[hello world tutorial].

Explore all xref:tutorials.adoc[tutorials].

