= Deploying Cluster-Side Modules to {hazelcast-cloud} Clusters
:description: Before clusters can execute or store your xref:cluster-side-modules.adoc[cluster-side modules], they need to be packaged into a single file and uploaded to the cluster as custom classes. You can upload cluster-side modules, using the console, or the Maven plugin.

{description}

== Before you Begin

Check the xref:cluster-side-modules.adoc#prereqs, [requirements and limitations] for cluster-side modules to make sure that your code is ready to be packaged.

[[package]]
== Uploading Cluster-Side Modules

Clusters expect all modules to be packaged into a single ZIP or JAR file. When you’ve built and packaged your cluster-side modules, the final step is to upload the resulting package file to the cluster.

You can upload custom classes, using the following options:

- Maven plugin
- Hazelcast {hazelcast-cloud} console

=== Using the Maven Plugin
[.serverless]*Hazelcast {hazelcast-cloud} Serverless*

. xref:maven-plugin-hazelcast.adoc[Configure the Hazelcast {hazelcast-cloud} Maven plugin] in your `pom.xml` file.

. Change into your project's root directory.

. Execute the `deploy` goal to package your project into a JAR file and upload it to the configured cluster.
+
```bash
mvn clean package hazelcast-cloud:deploy
```

In the output, you should see that the plugin packaged and deployed your JAR to your {hazelcast-cloud} Serverless cluster.

=== Using the Hazelcast {hazelcast-cloud} Console

You must have either an xref:teams-and-users.adoc[admin or developer role] to upload code to Hazelcast {hazelcast-cloud}.

. Use your build tool such as Gradle or Maven to package the classes into a JAR or ZIP file.

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console] and select your cluster.

. Go to *Upload Custom Classes* and use the file selector to upload the file to Hazelcast {hazelcast-cloud}.

When the file is uploaded and ready to use, you will see a success message.

== Removing Cluster-Side Modules

To remove cluster-side modules from the cluster, you must use the Hazelcast {hazelcast-cloud} console.

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console] and select your cluster.

. Click *Upload Custom Classes* and find your class in the list.

. Click on the delete icon next to the class that you want to delete.

== Downloading Cluster-Side Modules

To download a cluster-side module, you must use the Hazelcast {hazelcast-cloud} console.

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console].

. Click *Upload Custom Classes*, find your class in the *Uploaded Classes* list and click on it.
