= Migrate Data to another Cluster
:description: In this tutorial, you'll use xref:wan-replication.adoc[WAN Replication] to migrate data from one cluster to another.

== Before you Begin

You cannot use WAN Replication if your cluster has developer mode turned on.

You need at least two clusters with the same configuration. For example, if one cluster
contains xref:custom-classes-upload.adoc[custom classes] or Persistence,
you should enable and configure these options for the other cluster as well.

== Step 1. Create WAN Replication

In order to create WAN Replication, you can go to *Cluster Detail* > *Settings* > *Wan Replication* and click *Create New Replication*

After setting all these parameters, you can click *Next* to select and configure consumer cluster.

Settings on this screen for consumer cluster are same as publisher cluster except *Active/Passive* section. If you set consumer cluster as *Active*, data will be synchronized from/to publisher and consumer. If you set consumer cluster as *Passive*, data will be sent only from publisher to consumer.
Once you configured settings for consumer, you can click *Save*

Within seconds, wan replication will be ready there.

Once it is finished, you can verify it by going to Management Center *Cluster Detail* > *Management Center* > *Enable*  then *Management Center* > *Open Management Center*.

When you connect publish cluster and try to write some data, you will see data will be replicated to consumer cluster.

NOTE: You can synchronize all data by using *Sync* button in the WAN replication settings.

== Step 2. Connect to a Cluster

After migration is done, you can connect to a new cluster with a different client such as the xref:java-client.adoc[Java client].

== Step 3. Delete the Old Cluster

You can delete your old cluster once migration finished and clients connected to a new cluster.

NOTE: WAN replication must be deleted before cluster deletion