= {hazelcast-cloud} Dedicated Clusters
:description: Dedicated is a managed cloud service that allows you to maintain control over the hardware, resources, and deployment options that are available to your cluster. Dedicated means you get specific servers (cloud instances) all to yourself. 
:page-dedicated: true
:cloud-tags: Get Started
:cloud-title: About Dedicated
:cloud-order: 12
:page-aliases: scale-up-down.adoc, hazelcast-version.adoc 

{description}

You can design a Hazelcast topology that meets your specific compliance and service design needs.

- Data and security regulations
** Deploy your clusters to specific regions to comply with data residency laws.
** Benefit from strict container isolation for projects that require enhanced security. {hazelcast-cloud} Dedicated is SOC 2 and ISO 27001 compliant.

- Service design
** Specify the number of members in your clusters as well as their memory capacity. You decide when to xref:scale-up-down.adoc[scale your clusters] if they need more resources.  
** Deploy clusters to specific regions or cloud providers as part of your organization's cloud strategy.  To reduce network latency, you can deploy clusters in regions that are closest to your users' locations.
** Benefit from Hazelcast support and predictable monthly billing.

{hazelcast-cloud} Dedicated clusters are suitable for lightweight or production-critical applications where the workload is generally predictable.

== Next Steps

- xref:create-dedicated-cluster.adoc[]
