= Delete Organization
:description: pass:q[If you no longer need to access your clusters, you can delete your organizaton. To avoid additional charges while your clusters are not in use, consider xref:stop-and-resume.adoc[pausing] them instead.]
:cloud-tags: Organizations and Accounts
:cloud-title: Delete Organization
:cloud-order: 60
:toclevels: 3

{description}

You cannot delete an organization while there are outstanding payments on the account.

If the organization is deleted, all associated users, clusters, and resources are also deleted. If you need to keep any data, ensure that you have migrated it before deleting the organization.

NOTE: You can remove organization users from your organization at any time through the User Management screen. For further information on removing organization users, see the xref:remove-user.adoc[Remove User] topic.

Deleting an organization removes the following:

- Clusters associated with the organization, including any data such as data structures, custom classes, backups, and configuration
- Account and payment details
- Billing information
- The admin user account
- All organization user sign ins

NOTE: You might continue to receive occasional marketing communications from Hazelcast. See our link:https://hazelcast.com/privacy/[privacy policy^] for more details.  

Hazelcast recommends that you copy any data or details that you might need in the future. You cannot recover any data from a deleted account.

To delete an organization, complete the following steps:

. Open the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Select *Organization* from the side navigation bar
. Select *Password* from the *Account* options
+
The Info screen displays.

. Scroll down to the *Danger Zone* section of the Info screen

. Select the *DELETE THIS ORGANIZATION* button
+
A confirmation dialog box displays.
+
WARNING: If you delete the organization, all users, clusters, and other resources associated with the organization are also deleted.

. Enter the admin user's email address in the *Your email* text box
. Enter `delete my account` in the *To verify, type "delete my account" below:* text box
. Select the *DELETE THIS ORGANIZATION* button
+
WARNING: There is no confirmation dialog box. If you select the *DELETE THIS ORGANIZATION* button the users, clusters, and cluster data associated with your account are deleted immediately. This step is irreversible.

NOTE: If the organization has an outstanding balance, it cannot be deleted until the balance is cleared. Payment is attempted using the provided payment method, if successful, the organization is deleted. For further information on billing and payments, see the xref:payment-methods.adoc[Billing and Payments] section.

When you delete your account, no further charges are incurred and you cannot access your account.
