= Creating API Keys
:url-cloud-developers: https://cloud.hazelcast.com/settings/developer
:description: To connect a client to your {hazelcast-cloud} account, you need an API key and an API secret. These credentials authenticate clients to your account. You can manage these credentials in your account settings in {hazelcast-cloud}.

{description}

To manage API keys for a team's cluster, you must have either an xref:create-account.adoc#roles[admin or developer role].

== Using the {hazelcast-cloud} Console

// tag::create[]
To create a new set of API credentials, do the following:

. Sign into the link:{page-cloud-console}[{hazelcast-cloud} console].
. Click the *Account* icon in the bottom left corner.
. Click *Developer*.
. Click *Generate new API Key*.
// end::create[]

You can use these credentials in your applications to manage all clusters in your account. Currently, you can only create one API key and secret pair on your account.

IMPORTANT: Keep your keys and secrets secure. Anyone who has these credentials can delete your clusters.

== Deleting an API Key

You can delete your API key at any time by clicking the *Delete API Key* button.

WARNING: After you delete your API key, any application that uses this key will no longer work unless you configure them with a new set of credentials.
