= Creating API Keys
:description: To connect a client to your account, you need an API key and an API secret. These credentials authenticate clients to your account. You can manage these credentials in your account settings.
:cloud-tags: Manage Accounts
:cloud-title: API keys
:cloud-order: 32

{description}

== Using the Hazelcast {hazelcast-cloud} Console

// tag::create[]
To create a new set of API credentials, do the following:

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Go to *Account* > *Developer*.
. Click *Generate New API Key*.
// end::create[]

You can use these credentials in your applications to manage all clusters in your account. Currently, you can only create one API key and secret pair on your account.

IMPORTANT: Keep your keys and secrets secure. Anyone who has these credentials can delete your clusters.

== Deleting an API Key

You can delete your API key at any time by clicking the *Delete API Key* button.

WARNING: After you delete your API key, any application that uses this key will no longer work unless you configure them with a new set of credentials.
