= Failover Clients with Hazelcast Cloud
:description: In this tutorial, you'll configure the Hazelcast Java client to connect to a failover cluster when it cannot connect to the primary cluster.

{description}

== Context

Failover is an important feature of systems that rely on near-constant availability. Hazelcast fault tolerance automatically and transparently redirects your connection from one cluster that has problems to the second running cluster.

== Before you Begin

You need to xref:create-serverless-cluster.adoc[create more than one cluster] on Hazelcast Cloud.

== Create the Client Configuration

You need to create a client configuration for each cluster you want to use.
In order to do that you should have the following:

- Cluster Name
- Discovery Token
- Password

You can get this information from a popup that opens when you click the *Connect your Application*.

As soon as you successfully collect needed information for every cluster, you are ready to create your client configurations as shown below for different Hazelcast Versions.

[tabs] 
====
Hazelcast 4.x:: 
+ 
--
[source,java]
----
public static ClientConfig getPrimaryClientConfig() {
  String discoveryToken = "CLUSTER_DISCOVERY_TOKEN";
  String clusterName = "YOUR_CLUSTER_NAME";

  ClientNetworkConfig clientNetworkConfig = new ClientNetworkConfig();
  ClientCloudConfig cloudConfig = new ClientCloudConfig()
    .setDiscoveryToken(discoveryToken)
    .setEnabled(true);
  clientNetworkConfig.setCloudConfig(cloudConfig);

  ClientConfig config = new ClientConfig();
  config.setNetworkConfig(clientNetworkConfig);
  config.setClusterName(clusterName);
  config.setProperty(STATISTICS_ENABLED.getName(), "true");
  return config;
}
----
--
Hazelcast 3.x:: 
+ 
--
[source,java]
----
public static ClientConfig getPrimaryClientConfig() {
  String clusterName = "YOUR_CLUSTER_NAME";
  String clusterPassword = "YOUR_CLUSTER_PASSWORD";
  String discoveryToken = "YOUR_CLUSTER_DISCOVERY_TOKEN";

  ClientConfig config = new ClientConfig();
  config.setGroupConfig(new GroupConfig(clusterName, clusterPassword));

  ClientNetworkConfig clientNetworkConfig = new ClientNetworkConfig();
  ClientCloudConfig cloudConfig = new ClientCloudConfig()
    .setDiscoveryToken(discoveryToken)
    .setEnabled(true);
  clientNetworkConfig.setCloudConfig(cloudConfig);

  config.setNetworkConfig(clientNetworkConfig);
  config.setProperty("hazelcast.client.statistics.enabled", "true");
  return config;
}
----
--
==== 

== Create Failover Client

You can create a failover client by providing every client configuration for different Hazelcast Cloud clusters.

[source,java]
----
ClientFailoverConfig clientFailoverConfig = new ClientFailoverConfig();
//First Cluster
clientFailoverConfig.addClientConfig(getPrimaryClientConfig());
//Second Cluster
clientFailoverConfig.addClientConfig(getSecondaryClientConfig());
//Other Clusters Optionally
.
.
.
  
HazelcastInstance client = HazelcastClient
  .newHazelcastFailoverClient(clientFailoverConfig);
----

== Check Failover In Action

When you complete all the steps above, you are ready to go and try failover with Hazelcast Cloud.
You can easily simulate a failover by stopping or deleting one of the clusters that you provided in the failover configuration. After you do that, you will see that your client will try to connect the other clusters one by. You will see a message on your console that says it will use a different cluster.

```
INFO: hz.client_1 [my-primary-cluster] [4.0] Unable to connect to any address from the cluster with name: my-primary-cluster. The following addresses were tried: [[-], [-]]

INFO: hz.client_1 [my-primary-cluster] [4.0] Resetting local state of the client, because of a cluster change 

INFO: hz.client_1 [my-secondary-cluster] [4.0] Trying to connect to next cluster: my-secondary-cluster
```
