= Java Hello World
:description: This tutorial shows you how to get started with Hazelcast Cloud quickly. You'll create a Hazelcast Serverless cluster, and then use the Java client to add some entries to a map.

{description}

== Before you Begin

You need a xref:create-account.adoc[Hazelcast Cloud account].

== Step 1. Start a Hazelcast Cloud Cluster

In the Hazelcast Cloud console, do the following:

include::create-serverless-cluster.adoc[tag=development] 

== Step 2. Run the Sample Client

. Open the Hazelcast Cloud console and click *Connect your Application*.



`Connection Successful!` in your logs means that your client application has successfully connected to your cluster in Hazelcast Cloud. The sample client code adds random entries to a map in your cluster. In your Hazelcast Cloud console, you should see the charts begin to be populated with metrics of your map.

Also, you can see your client listed under *Client Statistics* at the bottom of your cluster's page.

== Client Code

To help you understand how the client connected to the cluster, this section explains some of the source code. 

TIP: The code for this sample client is hosted on link:https://github.com/hazelcast/hazelcast-cloud-java-sample-client/tree/5.1/src/main/java/com/hazelcast/cloud/ClientWithSsl.java[GitHub].

.ClientWithSsl.java
[source,java]
----
public class Client {

  public static void main(String[] args) throws InterruptedException {
    ClientConfig config = new ClientConfig(); <1>

    <2>
    ClassLoader classLoader = ClientWithSsl.class.getClassLoader();
    Properties props = new Properties();
    props.setProperty("javax.net.ssl.keyStore", classLoader.getResource("client.keystore").getPath());
    props.setProperty("javax.net.ssl.keyStorePassword", "YOUR_KEY_STORE_PASSWORD");
    props.setProperty("javax.net.ssl.trustStore", classLoader.getResource("client.truststore").getPath());
    props.setProperty("javax.net.ssl.trustStorePassword", "YOUR_KEYSTORE_PASSWORD");

    ClientConfig config = new ClientConfig();
    config.getNetworkConfig().setSSLConfig(new SSLConfig().setEnabled(true).setProperties(props));

    config.setClusterName("YOUR_CLUSTER_NAME"); <3>

    config.setProperty("hazelcast.client.statistics.enabled","true"); <4>

    config.setProperty(ClientProperty.HAZELCAST_CLOUD_DISCOVERY_TOKEN.getName(), "YOUR_CLUSTER_DISCOVERY_TOKEN"); <5>

    HazelcastInstance client = HazelcastClient.newHazelcastClient(config); <6>

    <7>
    IMap<String, String> map = client.getMap("map");
    map.put("key", "value");

    <8>
    if (map.get("key").equals("value")) {
      System.out.println("Connection Successful!");
      System.out.println("Now, `map` will be filled with random entries.");
    }
    else {
      throw new RuntimeException("Connection failed, check your configuration.");
    }

    Random random = new Random();

    <9>
    while (true) {
      int randomKey = (int) random.nextInt(100_000);
      map.put("key" + randomKey, "value" + randomKey);
      map.get("key" + random.nextInt(100_000));

      if(randomKey % 10 == 0 ) {
        System.out.println("map size:" + map.size());
      }

      Thread.sleep(100);
    }
  }
}
----

<1> Create an empty client configuration.

<2> Configure TLS encryption. You already downloaded these certificate and key files with the client code.

<3> Set the cluster name.
+
The cluster name is unique to your cluster. The client is authenticated using this cluster name.

<4> Enable Hazelcast to send the client statistics to the cluster's page.

<5> Set the discovery token.
+
This token is also unique to your cluster and used to discover Hazelcast cluster members.

<6> Create the client with `config`.
+
This step creates the connection between your application and the cluster.

<7> Get/create a map and put a simple entry ("key", "value").

<8> Check if the entry has been added successfully and let the code throw an exception if the value is not correct.

<9> Add random entries with 100-millisecond intervals. 

== Learn More

See the xref:hazelcast:clients:java.adoc#configuring-java-client[Java client documentation] for more information about using the Java client.