= Logging Integrations
:description: Hazelcast Dedicated allows to integrate your cluster logs with a remote log management system. With the correct setup, all Hazelcast members send their logs to the configured remote log management system.
:page-dedicated: true

{description}

NOTE: For Hazelcast Serverless, you can use the xref:maven-plugin.adoc[Maven plugin] to stream cluster logs back to your local environment. 

== Supported Log Management Systems

Currently, the following logging solutions are supported:

- ELK (Elastic Stack)
- Splunk

TIP: For a tutorial, see xref:shipping-logs-to-amazon-elasticsearch-service.adoc[]

== Setting up Logging Integration

To set up logging integration, do the following:

. Go to  *Manage Cluster* > *Settings* > *Logging*.

. Select the desired solution in the *Logging Technology* dropdown menu and provide the access parameters.

. Click *Create Logging Integration*. You should receive the Hazelcast member logs in your preferred log management system.

== Removing Logging Integration

. Go to  *Manage Cluster* > *Settings* > *Logging*.

. Click *Delete Logging Integration*.

The Hazelcast member logs are no longer sent out.

