= Logging Integrations for Hazelcast Dedicated
:description: Hazelcast Dedicated allows to integrate your own log management system. With the correct setup, all Hazelcast members send their logs to the configured remote logging integration.
:page-dedicated: true

{description}

NOTE: For Hazelcast Serverless, the Maven plugin will allow you stream cluster logs back to your local environment. This feature is in development. 

== Supported Log Management Systems

Currently, the following logging solutions are supported:

- ELK (Elastic Stack)
- Splunk

See our tutorial on xref:shipping-logs-to-amazon-elasticsearch-service.adoc[Shipping Logs to Amazon ElasticSearch]

== Setting up Logging Integration

To set up the logging integration, click on the *Manage Cluster* button in the cluster details page (Hazelcast Cloud console) and select *Settings*. Go to the *Logging* tab of the appeared 'UPDATE CLUSTER' dialog.

Select the desired solution in the *Logging Technology* dropdown menu and provide the access parameters. Below is a sample screenshot when "ELK" is selected.

Click on the *Create Logging Integration* button. You should receive the Hazelcast member logs in your preferred log management system.

You can always remove the defined logging integrations by first clicking on the *Manage Cluster* button in the cluster details page, selecting *Settings* and navigating to the *Logging* tab of the appeared 'UPDATE CLUSTER' dialog.

Click on the *Delete Logging Integration* and the Hazelcast member logs are no longer sent out.

