= Building a MapStore for {hazelcast-cloud}
:toclevels: 3
:url-code-sample-mapstore: https://github.com/hazelcast/hazelcast-cloud-code-samples/tree/master/mapstore
:description: pass:q[MapStore is an API for building a cache on top of Hazelcast. The MapStore interface includes methods that are triggered when operations are invoked on a map. You can implement your own logic in these methods to connect to an external data store, load data from it, and write data back to it. For example, you can use a MapStore to load data into your {hazelcast-cloud} cluster from a MongoDB, MySQL, or PostgreSQL database.]

{description}

MapStore supports the following caching patterns:

- *Read-through:* If an entry does not exist in memory when an application asks for it, Hazelcast asks the MapStore implementation to load that entry from the data store. If the entry exists, the MapStore implementation requests it from the data store and Hazelcast puts it into memory.
- *Write-through:* When new entries are added to a map, those entries are added to the data store synchronously.
- *Write-behind:* When new entries are added to a map, those entries are added to the data store asynchronously, after a configured delay.

MapStore extends the MapLoader interface with the methods to store and delete data in the external data source, whereas MapLoader contains the methods to load data into Hazelcast. You can use either of these interfaces to meet your requirements, but this guide refers to both interfaces as _MapStore_.

The following steps describe the workflow for developing a MapStore for {hazelcast-cloud}:

. <<implement, Implement>>
. <<test, Test>>
. <<deploy, Deploy>>
. <<configure, Configure>>

To use this feature, you must have either an admin or developer role. See xref:teams-and-users.adoc[].

[[implement]]
== Implementing a MapStore

To implement a MapStore for {hazelcast-cloud}, you can mostly xref:hazelcast:data-structures:working-with-external-data.adoc[follow the reference in the Hazelcast Platform documentation]. However, you must make sure to manage the lifecycle of the MapStore. When {hazelcast-cloud} loads the MapStore, it makes a connection to the external data store. If open connections are left open, these connections will consume unnecessary resources. To manage this connection, make sure to implement the link:https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/map/MapLoaderLifecycleSupport.html[`MapLoaderLifeCycleSupport` interface] to allow {hazelcast-cloud} to close connections to the data store on a graceful shutdown.

[[test]]
== Testing a MapStore

Before you deploy the MapStore to {hazelcast-cloud}, you should test the MapStore for the following:

- The MapStore connects to the data store without errors. Your data source should accept incoming connections from {hazelcast-cloud}.
- Operations on the map trigger your MapStore implementations. For a list of operations that trigger the MapStore, see the xref:hazelcast:data-structures:working-with-external-data.adoc#map-mapstore[Hazelcast Platform documentation]. You can xref:connect-to-cluster.adoc[use one of the available clients] to invoke map operations.

For general guidance on testing cluster-side modules, see xref:cluster-side-modules.adoc[].

[[deploy]]
== Deploying a MapStore

Before you can configure the MapStore, you need to deploy it by packaging your classes into a file along with any dependencies and uploading that file to {hazelcast-cloud}. See xref:custom-classes-upload.adoc[].

[[configure]]
== Configuring a MapStore

To use a MapStore, it must be configured for a specific map in {hazelcast-cloud}. When a map is configured with a MapStore, Hazelcast plugs the MapStore implementation into the lifecycle of the map so that the MapStore is triggered when certain map operations are invoked.

. Sign into the [.console]*link:{page-cloud-console}[{hazelcast-cloud} console]* and select your cluster.
. Go to *Data Structure Config* > *Add New Configuration*.
. Configure the map.
. In the bottom left corner, select *Enable MapStore*.
. Select a classname from the dropdown. If you don't see a classname, you need to deploy the MapStore to {hazelcast-cloud}.
. Configure the fields, depending on your requirements.
.. To configure a write-through cache, leave the *Write Delay Seconds* field set to 0.
.. To configure a write-behind cache, set the *Write Delay Seconds* field to the number of seconds that you want to wait before adding entries to the data store.
. Click *Save Configuration*.

=== Configuration Fields

The following are the descriptions of MapStore configuration elements and attributes:

- *Class Name*: Name of the uploaded file that contains the MapStore.

- *Write Delay Seconds*: Number of seconds to delay to call the `MapStore.store(key, value)`. If the value is zero then it is write-through, so the `MapStore.store(key, value)` method is called as soon as the entry is updated. Otherwise, it is write-behind; so the updates will be stored after the *Write Delay Seconds* value by calling the `Hazelcast.storeAll(map)` method. Its default value is *0*.

- *Write Batch Size*: Used to create batch chunks when writing map store. In default mode, all map entries are tried to be written in one go. To create batch chunks, the minimum meaningful value for write-batch-size is 2. For values smaller than 2, it works as in default mode.

- *Write Coalescing*: In write-behind mode, Hazelcast coalesces updates on a specific key by default; it applies only the last update on it. You can set this element to false to store all updates performed on a key to the data store.

- *Initial Mode*: Sets the initial load mode. *Lazy* is the default load mode, where the load is asynchronous. *Eager* means the load is blocked till all partitions are loaded. 

- *Properties*: The name/value properties that can be read inside the MapStore. For example connection credentials for a database. These properties are encrypted after you save the configuration.

== Updating a MapStore

To update a MapStore after you've deployed it, you must delete it and redeploy another one.

If the name of your MapStore class is the same as the one that you want to update, do the following:

. Click *Upload Custom Classes* and remove the file that contains your MapStore.
. Optional: <<test-mapstore, Test your new MapStore>>.
. <<deploy, Deploy>> the new version of your MapStore.

If the name of your MapStore class is the different to the one that you want to update, do the following:

. Click *Upload Custom Classes* and remove the file that contains your MapStore.
. Optional: <<test-mapstore, Test your new MapStore>>.
. <<deploy, Deploy>> the new version of your MapStore.
. <<configure, Reconfigure>> the MapStore.

== Next Steps

For sample projects that use a MapStore in {hazelcast-cloud}, see this link:{url-code-sample-mapstore}[GitHub repository].

Or, follow a xref:tutorials.adoc[tutorial].
