= Build a MapStore for Hazelcast {hazelcast-cloud}
:toclevels: 3
:url-code-sample-mapstore: https://github.com/hazelcast/hazelcast-cloud-code-samples/tree/master/mapstore
:description: pass:q[The Hazelcast map module classes in the link:https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/map/package-summary.html[Hazelcast Root API] provide in-memory data stores. The MapStore module classes allow you to integrate data from external data sources, such as a database, file-based data store, or Kafka. This means that, if the requested value is not available in the in-memory data store, Hazelcast can attempt to load it from your external data sources. You can also use MapStore to store or delete values in your external data source. You can implement your own logic in the MapStore methods.]

{description}

MapStore builds a cache on top of Hazelcast with defined triggers for operations on a map. You can build a MapStore using either of the following module classes, depending on your requirements:

- MapLoader allows you to load data to your cluster from external systems. It supports read-through caching only.
- MapStore allows you to extend the functionality offered by MapLoader to store and delete data in your external systems. This ensures that all your data stores are synchronized. It supports read-through, write-through, and write-behind caching.

The caching patterns are as follows:

[cols="h,2,4"]
|===
|Caching pattern |Supported by |Description

|Read-through
|MapLoader and MapStore
|If the requested entry is not present in memory, MapStore requests it from the data store. 

If present in the data store, the entry is loaded to the distributed map and remains in memory until removed.

|Write-through
|MapStore only
|Adds entries to the data store synchronously when added to a map.

|Write-behind
|MapStore only
|Adds entries to the data store asynchronously after a configured delay when added to a map.
|===

To develop a MapStore, you must do the following:

. <<implement, Implement a MapStore>>
. <<test, Test the MapStore>>
. <<deploy, Deploy the MapStore>>
. <<configure, Configure the MapStore>>

To <<update, update a MapStore>>, you must delete the existing MapStore and deploy a new one.

[[implement]]
== Implement a MapStore

When implementing a MapStore for {hazelcast-cloud}, you must manage the lifecycle to ensure that connections to the external data store are not left open. Closing the connections prevents them from consuming unneccessary resources. You can use the link:https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/map/MapLoaderLifecycleSupport.html[`MapLoaderLifeCycleSupport`] interface to clean up the resources on graceful shutdown, including closing the connections.

With this in mind, you can follow the  xref:hazelcast:data-structures:working-with-external-data.adoc[Hazelcast Platform documentation] to implement a MapStore. 

NOTE: When you have finished, return to this page to continue with the testing of your implementation.

[[test]]
== Test a MapStore

Before you deploy the MapStore to {hazelcast-cloud}, ensure that:

- The MapStore connects to the data store without errors. Your data source accepts incoming connections from your {hazelcast-cloud} cluster.
- Operations on the map trigger your MapStore implementations. For a list of operations that trigger the MapStore, see the xref:hazelcast:data-structures:working-with-external-data.adoc#map-mapstore[Hazelcast Platform documentation]. You can xref:connect-to-cluster.adoc[use one of the available clients] to invoke map operations.

For general guidance on testing cluster-side modules, see the xref:cluster-side-modules.adoc[] topic.

[[deploy]]
== Deploy a MapStore

Before you can configure the MapStore, you must deploy it. To do this, package your classes into a file that includes any dependencies and upload that file to the cluster. 

For further information on deploying your MapStore, see the xref:custom-classes-upload.adoc[] topic.

[[configure]]
== Configure a MapStore

To use a MapStore, it must be configured for a specific map in {hazelcast-cloud}. When a map is configured with a MapStore, Hazelcast plugs the MapStore implementation into the lifecycle of the map to trigger the MapStore when certain map operations are invoked.

To configure a MapStore, complete the following steps:

. Sign into the link:{page-cloud-console}[{hazelcast-cloud} console,window=_blank] and select your cluster.
. Select *Manage* > *Data Structures* from the navigation bar options, located on the left.
. Select the *Add New Configuration* button, located at the top right.
. Complete the fields to configure the map. 
+
For further information on the available fields, see the xref:map-configurations.adoc[Map Configuration] topic.

. Select the *Enable Map Store* checkbox, located at the bottom left.
+
Further fields display to configure the Map Store.
+
NOTE: If you have not deployed the MapStore to the cluster, the classname dropdown menu is not displayed. Deploy your MapStore before continuing.

. Select a classname from the dropdown menu. 
. Configure the fields according to your requirements. 
+
The fields are described in the <<config-fields, Configuration Fields>> section below.
+
[NOTE]
====
For a write-through cache, leave the *Write Delay Seconds* field set to `0`. 

For a write-behind cache, enter the time in seconds to wait before adding entries to the data store.
====

. Select the *Save Configuration* button.

[[config-fields]]
=== Configuration Fields

The MapStore configuration elements and attributes are as follows:

*Class Name*:: Select the MapStore you require from the dropdown menu. 
+
The menu options are populated with uploaded files containing MapStores.

*Write Delay Seconds*:: Enter the number of seconds to wait before calling the `MapStore.store(key, value)` method in the text box.
+
Default is *0*.
+
A value of zero defines a write-through cache. The `MapStore.store(key, value)` method is called as soon as the entry is updated. 
+
Any other value defines a write-behind cache. Updates are stored for the specified period using the `Hazelcast.storeAll(map)` method.

*Write Batch Size*:: Enter the number of map entries to include in each batch chunk when writing a map store. 
+
By default, each batch chunk contains a single entry. 
+
The minimum meaningful value is `2`. If you enter a value of less than 2, the default is used.
+
NOTE: If you do not have sufficient entries to form a complete batch chunk, the final entries are included in a smaller batch chunk after a timeout.

*Write Coalescing*:: Select or de-select the checkbox to determine how to store updates for a key.
+
NOTE: Applies only when using write-behind caching.
+
By default, Hazelcast combines updates on a key. 
+
De-select the checkbox to store all updates on a key.
+
Select the checkbox to store only the final update on a key that has been changed multiple times.

*Initial Mode*:: Select the initial load mode from the dropdown menu.
+
By default, lazy loading is used.
+
The menu options are as follows:
+
* *Lazy*. Select to use asynchronous loading. 
* *Eager*. Select to pre-load all partitions before loading. 

*Properties*:: Enter the name and value of a property, which can be read inside the MapStore, in the text boxes. 
+
For example, the connection credentials for a database. 
+
To add the specified property, select the *Add* button.
+
You can continue to add properties in the same way. 
+
NOTE: When you save the configuration, the properties are encrypted.

[[update]]
== Update a MapStore

To update a MapStore after you've deployed it, you must delete it and redeploy another one as follows:

. Select *Upload Custom Classes* and remove the file that contains your MapStore.
. Optionally, <<test-mapstore, Test your new MapStore>>.
. <<deploy, Deploy>> the new version of your MapStore.
. If the name of your MapStore class is different to the one that you are updating, <<configure, Reconfigure>> the MapStore.

== Next Steps

Build and run sample projects that use a MapStore in {hazelcast-cloud}. You can find the sample projects in the link:{url-code-sample-mapstore}[Hazelcast Cloud Code Samples GitHub repository].

Work through the xref:tutorials:ROOT:write-through-cache-serverless-mapstore.adoc[tutorial] to build an application that writes changes to a map back to MongoDB Atlas.
