= Multi-Factor Authentication
:description: Multi-factor authentication (MFA) adds another layer of security to your account. If enabled, instead of relying only on a username and password, MFA uses a trusted device to generate a secure digital identifier used to confirm your identity. By default, MFA is disabled.
:page-aliases: account-security.adoc
:cloud-tags: Manage Accounts
:cloud-order: 30

{description}

NOTE: If signing in with Google or GitHub, set MFA for those accounts and not for your {hazelcast-cloud} account. If you use social sign-in, MFA is not requested in the {hazelcast-cloud} console, even when enabled, as your username and password credentials have not been provided.

[[enable]]
== Enable Multi-Factor Authentication

If you have not set a password, you must do this before you can enable MFA. To set a password, complete the following steps:

. Select *Account* from the side navigation bar
. Select *Password* from the *Account* options
+
The Account Settings screen displays.

. Select the *RESET* button
+
An email is sent to the registered email address.

. Select the *RESET YOUR PASSWORD* link provided in the email
+
The {hazelcast-cloud} Reset Password screen displays.

. Enter the password you want to use in the *New Password* text box
. Enter the same password in the *Confirm Password* text box
. Select the *Reset Password* button

You must log back in to {hazelcast-cloud} using this password before you can continue.

To enable MFA, complete the following steps:

include::partial$mfa-enable.adoc[]
+
You must now enter a username and password, and then provide the verification code using the authenticator app each time you sign in.

. Sign out of the Hazelcast {hazelcast-cloud} console
. Sign in to your account using your username and password
. Use your authenticator app to complete your sign in

include::partial$mfa-change-device.adoc[]

[[disable]]
== Disable Multi-Factor Authentication

If you've enabled MFA, you can disable it at any time to sign in without an extra authentication step.

To disable MFA, complete the following steps:

include::partial$mfa-disable.adoc[]
