= Multi-Factor Authentication
:description: Multi-factor authentication (MFA) makes your account more secure by adding an extra step to the sign-in process. Instead of just entering a password, MFA allows you to use a trusted device to generate a secure digital pin for authentication.
:page-aliases: account-security.adoc
:cloud-tags: Manage Accounts
:cloud-order: 30

{description}

== Enabling Multi-Factor Authentication

. Install an authenticator app such as Google Authenticator on your device.
. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Click the *Account* icon in the bottom left corner.
. Click *Security*.
. Open your authenticator app and scan the QR code that is displayed in the Hazelcast {hazelcast-cloud} console. 
. Enter the 6 digit verification code into the input box in the Hazelcast {hazelcast-cloud} console and click *Enable two factor authentication*.
. Sign out and try signing in again.

After entering your username and password, you will be asked to enter the verification code, using the authenticator app.

Verification codes are specific to a particular device and cannot be transferred. If you switch to a new phone, you will need to <<disable, disable MFA>> before you do so, then re-enable it with your new phone.

[[disable]]
== Disabling Multi-Factor Authentication

If you've enabled MFA, you can disable it so that you can sign in without an authenticator app.

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Click the *Account* icon in the bottom left corner.
. Click *Security*.
. Click *Disable*.

You'll receive an email to confirm that MFA is disabled.
