= Multi-Factor Authentication
:description: If enabled at organization level, all users associated with the organization must enable Multi-factor Authentication (MFA). If disabled, users can choose whether or not to enable MFA for their sign-in. By default, MFA is disabled.
:page-aliases: account-security.adoc
:cloud-tags: Manage Accounts
:cloud-order: 30

{description}

Multi-factor authentication (MFA) adds another layer of security to your account. If enabled, instead of relying only on a username and password, MFA uses a trusted device to generate a secure digital identifer used to confirm your identity. 

NOTE: If signing in with Google or GitHub, set MFA for those accounts and not for your {hazelcast-cloud} account.

[[enable]]
== Enable Multi-Factor Authentication

To enable MFA for all users associated with your organization, complete the following steps:

include::partial$mfa-enable.adoc[]
+
. Select the *Enforce MFA* checkbox to enforce the use of MFA for all organization users

You and your organization users must now enter a username and password to sign in, and then provide the verification code using the authenticator app.

include::partial$mfa-change-device.adoc[]

[[disable]]
== Disable Multi-Factor Authentication

If you've enabled MFA, you can disable it at any time to allow you and your organization users to sign in without an extra authentication step.

To disable MFA for all users associated with your organization, complete the following steps:

include::partial$mfa-disable.adoc[]
