= Multi-Factor Authentication
:description: If enabled at organization level, all users associated with the organization must enable Multi-factor Authentication (MFA). If disabled, users can choose whether or not to enable MFA for their sign-in. By default, MFA is disabled.
:page-aliases: account-security.adoc
:cloud-tags: Manage Accounts
:cloud-order: 30

{description}

Multi-factor authentication (MFA) adds another layer of security to your account. If enabled, instead of relying only on a username and password, MFA uses a trusted device to generate a secure digital identifer used to confirm your identity. 

NOTE: If signing in with Google or GitHub, set MFA for those accounts and not for your {hazelcast-cloud} account. 

[[enable]]
== Enable Multi-Factor Authentication

If you have not set a password, you must do this before you can enable MFA. To set a password, complete the following steps:

. Select *Account* from the side navigation bar
. Select *Password* from the *Account* options
+
The Account Settings screen displays.

. Select the *RESET* button
+
An email is sent to the registered email address.

. Select the *RESET YOUR PASSWORD* link provided in the email
+
The {hazelcast-cloud} Reset Password screen displays.

. Enter the password you want to use in the *New Password* text box
. Enter the same password in the *Confirm Password* text box
. Select the *Reset Password* button

You must log back in to {hazelcast-cloud} using this password before you can continue.

To enable MFA, complete the following steps:

include::partial$mfa-enable.adoc[]
+
. To enforce the use of MFA for all organization users, select the *Enforce for entire team* toggle 

You and your organization users must now enter a username and password to sign in, and then provide the verification code using the authenticator app.

include::partial$mfa-change-device.adoc[]

[[disable]]
== Disable Multi-Factor Authentication

If you've enabled MFA, you can disable it at any time to allow you and your organization users to sign in without an extra authentication step.

To disable MFA for all users associated with your organization, complete the following steps:

include::partial$mfa-disable.adoc[]
