= Hazelcast {hazelcast-cloud}
:description: Hazelcast {hazelcast-cloud} simplifies deployments of Hazelcast Platform to the cloud. Hazelcast manages the underlying infrastructure allowing you to focus on building applications for stream and batch processing, low-latency querying, and caching.
:page-aliases: use-cases.adoc, faq.adoc, pricing.adoc, preface.adoc, wan-replication.adoc, support.adoc
:cloud-tags: Get Started
:cloud-title: Hazelcast Viridian Cloud Overview
:cloud-order: 10

{description}

Hazelcast {hazelcast-cloud} abstracts away the manual effort of managing physical servers or servers in the cloud so that you can focus on what matters: Building your application.

== Application Topology

{hazelcast-cloud} applications run in a client/server topology:

- {hazelcast-cloud} clusters are the servers that are responsible for storing and processing your data.

- Clients connect to your cluster to submit new processing jobs, request processing results, add data to storage, or query data.

== Editions

Hazelcast {hazelcast-cloud} has two editions: {hazelcast-cloud} Standard and {hazelcast-cloud} Dedicated.

xref:free-trial.adoc[{hazelcast-cloud} Trial] offers the capabilities of {hazelcast-cloud} Standard for a 14-day trial period.


[cols="1a,2a"]
|===
|Edition|Description

|xref:serverless-cluster.adoc[{hazelcast-cloud} Standard]
|{hazelcast-cloud} Standard clusters auto-scale, depending on the amount of data you store. 

|xref:dedicated-cluster.adoc[{hazelcast-cloud} Dedicated]
|To maximize security whilst minimizing latency, {hazelcast-cloud} Dedicated clusters expose only private Hazelcast endpoints. For consistent performance and throughput, {hazelcast-cloud} Dedicated clusters do not share infrastructure with any other customers.
|===

NOTE: When you first create an account on Hazelcast {hazelcast-cloud}, you become the administrator of an organization. For Trial Edition users, this has no further impact. For Standard and Dedicated Edition users, this means that you can invite users to your organization and share resources, such as clusters. For further information on organizations, see the xref:organizations-and-accounts.adoc[Organizations and Accounts] section.

== Getting Started

If you are a first-time user of Hazelcast {hazelcast-cloud}, see xref:get-started.adoc[].

If you're ready to get started with a real use case, see xref:tutorials.adoc[].

If you want to get an overview of the use cases and advantages of Hazelcast {hazelcast-cloud}, see the link:https://hazelcast.com/products/cloud/[Hazelcast website].

