= Hazelcast {hazelcast-cloud} Cloud Managed Services
:description: Hazelcast cloud managed services simplify deployments of Hazelcast Platform, allowing you to focus on building applications for stream and batch processing, low-latency querying, and caching.
:page-aliases: use-cases.adoc, faq.adoc, pricing.adoc, preface.adoc, support.adoc
:cloud-tags: Get Started
:cloud-title: Hazelcast Viridian Overview
:cloud-order: 10

{description}

Hazelcast {hazelcast-cloud} abstracts away the manual effort of managing physical servers or servers in the cloud so that you can focus on what matters: Building your application.

== Application Topology

Hazelcast {hazelcast-cloud} applications run in a client/server topology:

- {hazelcast-cloud} clusters are the servers that are responsible for storing and processing your data.

- Clients connect to your cluster to submit new processing jobs, request processing results, add data to storage, or query data.

== Editions

Hazelcast {hazelcast-cloud} offers two editions: {hazelcast-cloud} Serverless and {hazelcast-cloud} Dedicated.

[cols="1a,2a"]
|===
|Edition|Description

|xref:serverless-cluster.adoc[{hazelcast-cloud} Serverless]
|{hazelcast-cloud} Serverless clusters auto-scale, depending on the amount of data you store.

|xref:dedicated-cluster.adoc[{hazelcast-cloud} Dedicated]
|To maximize security whilst minimizing latency, {hazelcast-cloud} Dedicated clusters expose only private Hazelcast endpoints. For consistent performance and throughput, {hazelcast-cloud} Dedicated clusters do not share endpoints with any other customers.
|===

== Getting Started

If you are a first-time user of Hazelcast {hazelcast-cloud}, see xref:get-started.adoc[].

If you're ready to get started with a real use case, see xref:tutorials.adoc[].

If you want to get an overview of the use cases and advantages of Hazelcast {hazelcast-cloud}, see the link:https://hazelcast.com/products/cloud/[Hazelcast website].

