= Billing and Payments
:description: From the console, you can add payment cards to your account to pay for usage as well as view how much you've spent.
:cloud-tags: Manage Accounts | Manage Accounts | Manage Accounts
:cloud-title: Payments and Billing | Add Payment Card | View Bills
:cloud-order: 33 | 34 | 35
:cloud-anchor: | adding-a-payment-card | viewing-bills

{description}

For xref:serverless-cluster.adoc[{hazelcast-cloud} Serverless clusters], you must provide a payment card to do the following:

- Create two or more {hazelcast-cloud} Serverless clusters.
- Use more than 2 GiB of memory in a {hazelcast-cloud} Serverless cluster.

For xref:dedicated-cluster.adoc[{hazelcast-cloud} Dedicated clusters], you must provide a payment card to pay for new clusters or cluster usage for existing clusters.

== Adding a Payment Card

To set up automatic payments for your usage, add a payment card to your account.

NOTE: Hazelcast uses a third-party to store payment details and process payments. Payment details are not stored in Hazelcast.

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Click the *Account* icon in the bottom left corner.
. Click *Billing & Payments*.
. Click *Add Payment Method*.
. Complete the form by filling in your payment details.

You can add only one payment card to your account. To change the payment card, update it.

== Updating a Payment Card

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Click the *Account* icon in the bottom left corner.
. Click *Billing & Payments*.
. Click *Update Payment Method*.
. Complete the form by filling in your payment details.

Your updated card is charged for future payments.

== Removing a Card from your Account

You cannot remove payment cards from your account, using the Hazelcast {hazelcast-cloud} console.

To remove a payment card from your account, contact us at mailto:support@hazelcast.com[].

== Viewing Bills

You can see how much you've spent in the current month as well as previous invoices.

. Sign into the link:{page-cloud-console}[Hazelcast {hazelcast-cloud} console,window=_blank].
. Click the *Account* icon in the bottom left corner.
. Click *Billing & Payments*.

You can see how much you've spent in the current month as well as how much you spent in previous months.


