= What is Hazelcast Cloud?
:description: Hazelcast Cloud provides all the features of the in-memory storage and data processing engine in a simple cloud-based web application that's deployed and fully managed by Hazelcast. Leveraging over a decade of our experience and best practices, the result is a high-throughput low-latency service that scales to your needs while remaining simple to deploy.

{description}

== Simplicity and Reduced IT Costs

Hazelcast Cloud is easy to use and deploy. No dealing with servers and a bare minimum of configuration. We will maintain your Hazelcast instances using high-quality cloud instances and a high-performance network. You can stop your instances when you are not using them and scale up your cluster when necessary. Pay only for what you use.

See xref:manage-the-cluster.adoc[].

== Scalability and Flexibility

You can scale your cluster from MBs to hundreds of GBs in seconds with a single click.

See xref:manage-the-cluster.adoc#scaling-a-cluster[Scaling a Cluster].

== Up-To-Date Software

No need to worry about software updates. We will keep your software stack up-to-date with regular upgrades without causing any downtime on your application.

See xref:architecture.adoc[].

== Multi-Cloud

Hazelcast Cloud can be deployed on leading cloud providers, so you can choose the right one for your architecture.

See xref:create-enterprise-cluster.adoc[].

== Enterprise Features

Hazelcast Cloud gives you access to Enterprise features such as rolling upgrades, hot restart, security, and High-Density memory store.

== Rich Feature Set

Hazelcast is not solely a key-value store. Distributed maps are just one of the Hazelcast distributed data structures. By using Hazelcast Cloud, you will have access to the rich API, including distributed maps, multimaps, queues, topics, lists, sets and locks, as well as the other features.

== Distributed Architecture and High Performance

Hazelcast had been designed as a highly distributed system since day one. Utilizing multithreading, Hazelcast servers deliver higher performance when compared to older generation key-value stores.

== Comprehensive Security

Hazelcast Cloud makes use of all the security features included in Hazelcast Enterprise, including industry standard technologies like TLS and JAAS that are designed for large enterprises.

== Reliable Clients

Hazelcast has high-quality clients that are developed, maintained, and supported by Hazelcast. While developing your application, you will not cope with the issues and restrictions of an immature client.