= Plans and Pricing
:description: Hazelcast offers a free pricing plan as well as two paid plans that allow you to configure the amount of resources each cluster has, depending on your budget.

{description}

== Hazelcast Cloud Plans

Hazelcast Cloud has three plans.

[cols="a,a,a"]
|===
|Plan|Cost|Additional costs

|Serverless
|Free to store up to 2 GB, then $0.10 (USD) per GB
|None

|Dedicated
|Depends on the size of the chosen cloud instance
|<<dedicated, Data transfer and backup storage>>
|===

== Pricing for Serverless Clusters

Serverless clusters are billed monthly only for the amount of used storage. The first 2 GB of storage is free. If you use more than 2 GB, you are charged $0.10 per hour for every additional GB of used storage, not including the first 2 GB.

For example, you have an empty cluster. You load 3 GB of data into the cluster, run a query, and remove the data. For one hour, your cluster stored 3 GB data, and then the cluster remained empty for the rest of the month. You are billed for 1 GB for one hour, which is $0.10.

These examples show the cost per month of three clusters that each have a different memory capacity and uptime:

[cols="a,a,a,a"]
|===
|Cluster|Used storage|Time|Cost

|1
|1 GB
|Unlimited
|Free

|2
|2 GB
|Unlimited
|Free

|3
|10 GB
|10 minutes
|8 GB * 10/60 * 0.1 = $0.13

|===

You don't pay for backup replicas of your data.

Examples of what is included in storage:

- Data in data structures
- Indexes
- Stateful computations

[[dedicated]]
== Pricing for Dedicated Clusters

Dedicated clusters are charged for the following:

- *Provisioned memory:* How many resources you asked for when we created the cluster for you.
- Data transfer: The volume of data going into, out of, and within your clusters.
- *Backup storage:* If you requested persistence for your data, this is the cost of storing your backups in cloud storage.

=== Provisioned Memory

Hazelcast charges you a fixed amount, depending on how much memory capacity is reserved for your cluster. If your cluster has 10 GB capacity but you do not use all that memory, you are still charged for the full 10 GB because this amount of memory was reserved for your use.

These examples show the cost per month of three clusters that each have a different memory capacity and uptime:

[cols="a,a,a,a"]
|===
|Cluster|Memory|Total uptime per month|Cost

|1
|10 GB
|10 hours
|10 X 10 X $0.10 = $10.00

|2
|1 GB
|100 hours
|1 X 100 X $0.10 = $10.00

|3
|3 GB
|50 hours
|3 X 50 X $0.10 = $15.00

|===

In this scenario, the total cost for the month for all three clusters will be: $10.00 + $10.00 + $15.00 = $35.00

Dedicated clusters also incur charges for data transfer costs and any backup storage costs.

=== Data Transfer

Data transfer costs account for the volume of data going into, out of, and within your clusters.

Your data transfer charges are aggregated over the month and added to your monthly bill.

=== Backup Storage

If backups are enabled on your cluster, Hazelcast stores those backups in cloud storage, which comes with additional costs.

Backup storage costs depend on the cloud providers cost of storing the backups in their object store such as S3 on AWS.

== Custom Plans

Hazelcast offers custom pricing plans. To discuss a custom plan, contact us at mailto:sales@hazelcast.com[].

== Related Resources

Track your usage and current billing total.

Manage your billing and payment information.
