= Release Notes
:url-cloud-cli-announcement: https://hazelcast.com/blog/announcing-hazelcast-cloud-cli/
:url-cloud-sdk-announcement: https://hazelcast.com/blog/announcing-hazelcast-cloud-go-sdk/
:cloud-tags: Get Started
:cloud-order: 16

== September 9, 2022 - v4.0 BETA

This release introduces a BETA version of the xref:serverless-cluster.adoc[Hazelcast {hazelcast-cloud} Serverless] edition of Hazelcast {hazelcast-cloud} Cloud Managed Services. xref:tutorials.adoc[Tutorials] and xref:serverless-cluster.adoc[documentation] for Hazelcast {hazelcast-cloud} are also available.

*New Features*

- Development and production clusters for Hazelcast {hazelcast-cloud} Serverless. 

- Microsoft Authenticator is officially supported for multi-factor authentication.

- Event tracking is enabled to gather cluster usage metrics.

*Enhancements*

All enhancements are for the Hazelcast {hazelcast-cloud} Serverless edition of Hazelcast {hazelcast-cloud} Cloud Managed Services unless otherwise stated.

- Multiple UI improvements, including usability improvements to graphs showing cluster metrics and customer emails.

- To optimize resource consumption, idle Hazelcast {hazelcast-cloud} Serverless clusters are paused after 24 hours and an email is sent to the account holder.

- When you download log files from the console, the file name now includes the cluster name and the date/time of download.

*Fixes*

All bug fixes are for the Hazelcast {hazelcast-cloud} Serverless edition of Hazelcast {hazelcast-cloud} Cloud Managed Services unless otherwise stated.

- When you stop WAN Replication on a cluster, replication no longer restarts after autoscaling.

- When WAN replication is configured for a pair of clusters, metrics for map replications on both clusters are now displayed.

- To avoid issues with WAN Replication, any configuration changes that update network policies are now checked to make sure they do not restrict access between the publisher and the consumer cluster.

- When you stop and resume a cluster, the current figure for data usage is displayed immediately.

- When you stop a cluster, you can no longer add or remove IP address from the allow list because this change cannot be applied.

- When you delete a cluster, the confirmation message is no longer displayed before the deletion is complete.

- Backups of clusters with custom classes uploaded no longer fail to restore.

- Adding an IP address to the allow list no longer triggers a Java exception error.

- With MapStore enabled, you can now successfully upload MapStore classes from the *Custom Data Configuration* screen.

- Clusters no longer remain in the _Updating Cluster Config_ state for a long time while custom classes are uploaded.

- Configuring WAN replication for Enterprise clusters using Google Cloud Platform no longer incorrectly removes existing ConfigMaps.

- On the console of an Enterprise cluster with TLS disabled, the *Connect Your Application* button is no longer enabled until a peering connection is set up. 

== September 1, 2022 - v3.12.2

This release included improvements to cluster metrics for our support teams.

== August 26, 2022 - v3.12.1

This release included improvements to our backend email services.

== August 24, 2022 - v3.12.0

*Fixes*

- The quickstart guides for sample clients now provide the correct commands for clusters that have TLS enabled.

- The *Stop* button is no longer hidden on the dashboard of Enterprise clusters that are hosted on AWS or Azure.

- When you delete a WAN Replication configuration, the configuration is now deleted instead of being paused and resumed when you try to add a new configuration.

- When a cluster has WAN Replication and fails, you can now delete the active or passive cluster that is connected to that cluster.

== August 5, 2022 - v3.11.0

*New Features*

- Sample client applications now include examples of real-time processing.

*Fixes*

- Multiple UI updates and fixes.

== July 12, 2022 - v3.10.0

*New Features*

- The xref:maven-plugin-hazelcast.adoc[Hazelcast Maven Plugin] is now publicly available in the central maven repository.

*Fixes*

- UI updates for customer billing and cluster management screens.
- Standard clusters no longer fail while autoscaling.
- Clusters can now be restored from backups after autoscaling.

== June 15, 2022 - v3.9.0

*New Features*

- The Hazelcast Cloud CLI now supports commands for working with custom classes in Enterprise clusters.

*Fixes*

- Multiple improvements to WAN replication performance and stability.
- Various UI updates for cluster management processes.
- Data in Enterprise clusters is no longer overwritten when the memory limit is reached.
- .NET clients can now connect to clusters without errors.

== Jun 01, 2022 - v3.8.0

*Fixes*

- Multiple UI updates and fixes.
- Standard clusters no longer fail to resume after being stopped.

== May 6, 2022 - v3.7.0

This release is focused on improving the stability of Hazelcast Cloud, notably occasional failures during cluster lifecycle changes (creation, starting, stopping).

== March 25, 2022 - v3.6.0

*New Features:*

This release introduces Hazelcast 5.1 and the improvements to SQL:

- SQL support for aggregating streams into tumbling and hopping windows, sometimes known as sliding windows.  This then gives you the ability to run functions and aggregations such as sum or count that is snapped to a time window.
- Ability to create views, create indexes and run troubleshooting explain plans.
- union, union all, right join, exists and not exists.  
- JSON records with nested fields can be indexed and queried

== February 10, 2022 - v3.5.0

*New Features:*

- Support for {cpp} apps. Follow our xref:get-started.adoc[tutorial] to connect your {cpp} app to the cloud, and use the latest features of Hazelcast!

- A new compact design for the cluster page. 

*Fixes:*

- Fixed issue with resuming multi-zone AWS clusters.

- Fixed UI issues with map configuration.

- Fixed issue with syncing custom classes among cluster members.

== January 20, 2022 - v3.4.0

*New Features:*

- Introducing SQL for Python and Node.js. xref:get-started.adoc[Try the new SQL features] from your Python and Node.js apps.

- Lots of improvements in the UI.

- Improved Hazelcast 5 support. Hazelcast {hazelcast-cloud} now runs on the latest 5.0.2 version. 

- You can no longer create Hazelcast 3 clusters in the Cloud as they reached the end of support. Existing clusters are unaffected.

== December 3, 2021 - v3.3.0

*New Features:*

- Support for Hazelcast Platform 5.0. xref:get-started.adoc[Try the new SQL features].

- Contextual help to guide you through the process of configuring data structures.

- Lots of backend improvements to our service quality, security, and performance.

== October 4, 2021 - v3.1.0

*New Features:*

- We've changed our pricing model and introduced three plans: Basic, Standard, and Enterprise.

- You can now stop and resume clusters on the Enterprise plan. When a cluster is resumed, any persisted data is restored from disk. See xref:stop-and-resume.adoc[].

*Fixes:*

- Cluster names can now include up to 200 characters without breaking the layout.

*Enhancements:*

- Multi-factor authentication (MFA) is no longer restricted to just Google Authenticator.

== May 11, 2021 - v2.8.3

*Fixes:*

- Hazelcast Starter Discovery returns correct values for suspended clusters

== April 16, 2021 - v2.8.2

*Fixes:*

- The latest stable Kubernetes version are used on Azure

== April 9, 2021 - v2.8.1

*Fixes:*

- During cluster deletion, Azure storage accounts are now also deleted
- Field labels now match the placeholder text
- WAN Replication no longer fails on Azure clusters

== April 7, 2021 - v2.8.0

*New Features:*

- Hazelcast IMDG 3.12.12 is available in Starter and Enterprise
- UI persists last console location

*Fixes:*

-  Fixed an issue with custom classes
-  Fixed an issue with cluster state inconsistency
-  Fixed an issue with console log in

*Enhancements:*

-  Cluster monitoring and alerting improvements
-  Improved the message for the resetting password and signup operations

== March 9, 2021 - v2.7.3

*Fixes:*

-  Fixed an issue with token generator

== February 17, 2021 - v2.7.2

*Fixes:*

-  Fixed an issue with Logging Integration in Hazelcast Enterprise

== February 9, 2021 - v2.7.1

*Fixes:*

-  Fixed an issue with GitHub OAuth
-  Fixed an issue with applying promo codes
-  Fixed an issue with the custom classes uploaded to GCP

== February 8, 2021 - v2.7.0

*New Features:*

- Introduced Social Sign-On with Google and GitHub. You can now start using Hazelcast {hazelcast-cloud} with a few clicks.
- Hazelcast 4.1 in the cloud now

*Fixes:*

- Improve customer invitation and signups
- Several improvements with GCP Enterprise Clusters

== January 29, 2021 - v2.6.4

*Fixes:*

-  Fixed an issue with payment approvals

== January 25, 2021 - v2.6.3

*Fixes:*

-  Fixed an issue with metric calculations

== December 17, 2020 - v2.6.2

*Fixes:*

-  Fixed an issue with users Invitation and decommissioning

== December 2, 2020 - v2.6.1

*Fixes:*

-  Fixed an issue in the GCP Enterprise cluster scale-up

== December 1, 2020 - v2.6.0

*New Features:*

- Introduced GCP Cloud Provider support, now you can create an Enterprise cluster on GCP
- Official link:{url-cloud-cli-announcement[Hazelcast {hazelcast-cloud} CLI] is released
- Official link:{url-cloud-sdk-announcement[Hazelcast {hazelcast-cloud} Golang SDK] is released
- Unified VPC Peering flow. Now you can handle VPC Peering flow by using hzcloud cli for all cloud providers

*Fixes:*

- UK Post Code validation in the Payment Method screen is fixed.

== September 17, 2020 - v.2.5.0

*New Features:*

- Cluster management API using GraphQL
- Added the ability to reset token/password

*Fixes:*

- Fixed an issue where some clusters were failing during creation
- Fixed an issue in Map loader upload
- Improve the Cluster listing page speed

== September 7, 2020 - v2.4.1

*Fixes:*

- Fixed an issue where a stopped cluster couldn't be deleted

== September 2, 2020 - v.2.4.0

*New Features:*

- IMDG 4.0 clusters are now available in Cloud Starter
- Added a Description field for IP Whitelisting entry

*Fixes:*

- Fixed an issue where User was asked to pay the credits when trying to delete a public cloud account
- Fixed an issue with Management Center IP whitelisting not working correctly
- Fixed an issue where the Cluster Start time was showing incorrectly on the UI
- Added confirmation popup on WAN replication deletion
- Several UI improvements

== August 6, 2020 - v2.3.0

*New Features:*

- Support for xref:maploader-and-mapstore.adoc[MapLoader And MapStore]
- Support for Azure Cluster creation

== June 8, 2020 - v2.2.0

*New Feature:*

- Support for Hazelcast 4.0

== June 2, 2020 - v2.1.1

*Fixes:*

- Fixed an issue where Team couldn't create a cluster

== May 14, 2020 - v2.1.0

*New Features:*

- Public Access Option For Enterprise
- Public IP Whitelisting Support
- xref:wan-replication.adoc[WAN Replication]

== March 31, 2020 - Cloud Enterprise GA on AWS (v2.0.0)

*New Features:*

- Support for cluster creation and management in AWS.
- Connection via xref:aws-vpc-peering.adoc[AWS VPC peering].
- Connection via xref:aws-private-link.adoc[AWS Private Link]
- Replication to multiple xref:availability-zones.adoc[Availability Zones].
- xref:scale-up-down.adoc[Scale Up / Down] for Clusters
- TLS encryption for the data in transit.
- xref:logging-integration.adoc[Logging integration].
- xref:custom-classes-upload.adoc[Custom Classes upload] to support user defined objects.
- Support for all the Hazelcast data structures.
- Support for xref:java-client.adoc[Java], xref:net-client.adoc[.NET],  xref:nodejs-client.adoc[Node.js], xref:python-client.adoc[Python] and xref:go-client.adoc[Go] and clients.

== August 9, 2019

Hazelcast version has been updated to 3.12.2.

== June 19, 2019

*New Features:*

- Team and role-based access support
- More flexible credit (voucher) system

== May 16, 2019

*New Features:*

- xref:account-security.adoc[Multi-Factor Authentication] support has been added

*Fixes:*

- Promo code confirmation position not intuitive
- Add button for indexes overflow on Firefox
- Field validation on login screen triggered when clicking to `Forgot your password` link
- Custom map config dialog moves row height on error
- Credit card icon is distorted on Firefox

== March 19, 2019 - Hazelcast {hazelcast-cloud} 1.0

- Completed the Beta stage and launched Hazelcast {hazelcast-cloud} 1.0 GA.
- New UI for login and registration.

== March 15, 2019

*New Features:*

- Enabled the xref:hazelcast:clusters:deploying-code-on-member.adoc[User code deployment feature] for Hazelcast {hazelcast-cloud}. You can now run the executor service, entry processor and queries with custom objects.

*Fixes:*

- Added the missing import statement for the Go-lang example.

== March 4, 2019

*Fixes:*

- Added the missing TLS password for the downloadable sample clients.

== February 24, 2019

*Enhancements:*

- Added more explanation (tooltip) for autoscaling.
- Removed the unused static files.
- Improved the misleading label when creating a new cluster.

*Fixes:*

- Fixed an issue where the "New Cluster" page was blank when you visit it sequentially by manually entering in the browser.
- Fixed several typos on the emails.
- Fixed an issue where the dashboard and client API was showing different map sizes.

== January 28, 2019

*New Features:*

- IP Whitelisting: Introduced xref:ip-white-list.adoc[IP whitelisting] that allows you to restrict the clients that can connect to your cluster.
- Autoscaling: Introduced xref:scale-up-down.adoc[automatic scaling] (out or in) of your cluster depending on the memory utilization.

*Enhancements:*

- Introduced a page with maintenance warning to be shown during the Hazelcast {hazelcast-cloud}'s maintenance works.
- Improved the message for the resetting password operations requested by the users.
- Introduced a mechanism to clean up all the resources (map configurations, secrets, network policies, etc.) after a cluster is deleted.
- Added the allowed IP's field into the cluster details page.

*Fixes:*

- Fixed an issue where the "Billing & Payments" page was missing the invoice numbers.
- Added links to the past invoices and receipts under the "Billing & Payments" page.
- Fixed a validation issue where the UI was sending login requests for invalid form fields.
- Fixed the malfunctioning offline detection.

== January 11, 2019

*Enhancements:*

- Introduced a timeout to the metric query so that the cluster detail page is not destroyed.
- Improved the cluster detail page so that the chart panels are now hidden when the cluster is stopped.

*Fixes:*

- Fixed an issue where the Java client sample was not working since `mvnw` could not be executed.
- Fixed the issues in the Go client sample that caused indentation defects.
- Fixed an issue where the cluster details were still accessible for the deleted clusters.
- Fixed an issue where the "Cost this month" field under "Billing & Payment" page was not resetting.

