= {hazelcast-cloud} Serverless Clusters
:description: Serverless is a managed cloud service that offers a pay-as-you-go pricing model. Serverless clusters auto-scale to provide the resources that your application needs. You pay only for the resources that your application consumes.
:toc-levels: 3
:page-aliases: architecture.adoc
:page-serverless: true
:cloud-tags: Get Started
:cloud-title: About Serverless
:cloud-order: 11

{description}

Serverless means that Hazelcast manages the cloud infrastructure for you. Each {hazelcast-cloud} Serverless cluster is an independent deployment of Hazelcast Platform in a Kubernetes container. This design guarantees resource isolation, prevents resource stealing, and provides isolated network access.

== Beta Release

{hazelcast-cloud} Serverless is in beta while we continue to add new features.

Despite its beta state, you can use <<cluster-types, {hazelcast-cloud} Serverless production clusters>> for production applications.

== {hazelcast-cloud} Serverless Cluster Types

// tag::types[]
{hazelcast-cloud} Serverless clusters come in two types:

- *Development:* Capped storage. You can store at most 1 GiB of data.
- *Production:* Uncapped storage. The cluster scales as you add or remove data.
// end::types[]

[[dev]]
== Development Clusters

// tag::development[]
Development clusters are for fast, iterative development while you prototype your application.
// end::development[]

Development clusters have the following limitations:

- Maximum 1 GiB of storage
- Only a single member
- No cluster scaling
- No data backups
- No cluster data persistence

When a development cluster restarts for any reason, you lose cluster data, such as maps and cluster-side modules.

NOTE: You cannot convert a development cluster to a production cluster.

[[prod]]
== Production Clusters

// tag::production[]
Production clusters are for applications that have already been tested and are ready for deployment in real-world scenarios.
// end::production[]

Production clusters automatically scale out and in, depending on the amount of resources that you use.

=== Backups to Disk

Backup copies of your cluster data are stored on disk so that you can pause and resume your clusters when you want, without losing data. Cluster data consists of the following:

- Configuration settings
- Cluster-side modules
- Jobs
- Map and JCache data structures

Production clusters use the following backups:

- *Automatic backups:* A full backup of your cluster data is copied to disk once every 24 hours, and when a cluster is paused.
- *Manual backups:* You can take a xref:backup-and-restore.adoc[manual backup] of your cluster data at any time. Take up to a maximum of ten backups.

=== Backups to Other Members

By default, data on production clusters is backed up on one other member in the cluster.

Although you can configure some xref:data-structures.adoc[data structures] with a custom backup count, the effective backup count is limited by the number of members in your cluster. 

For example, if you configure a map with five backups, but your cluster has only two members, you will have one effective backup. You need to add enough data to the cluster so that it automatically scales up the number of members and backups to your configured count of five. 

== Restrictions on Free {hazelcast-cloud} Serverless Clusters

Development and production clusters are xref:stop-and-resume.adoc#pausing-a-cluster[paused] when both of these conditions are true:

- You don't connect to the cluster for 24 hours.
- You don't have a payment method set up for your Hazelcast {hazelcast-cloud} account.

If you're using a production cluster, Hazelcast saves your cluster data so that you can resume the cluster at a later time.

If you're using a development cluster, all cluster data is lost after the cluster is paused.

== Pricing for {hazelcast-cloud} Serverless Clusters

You pay only for what you store in RAM. Any data that is stored on disk or in backups to disk is free of charge. As a result, 'storage' is synonymous with RAM in {hazelcast-cloud} Serverless clusters.

{hazelcast-cloud} Serverless clusters are billed monthly only for the amount of storage that you use. The *first 2 GiB of storage in your account is free*. If you use more than 2 GiB across all your clusters, you are charged $0.10 per hour for every additional GiB of used storage, not including the first 2 GiB.

As well as the data that you add to data structures, such as maps, you are charged if you configure more than one backup of a data structure. Only the first backup is free.

Additional memory usage is also charged for, and may include the following:

- Indexes that you create
- Stateful jobs
- Serialization overhead

For example, the xref:cluster-side-modules.adoc#serializers[`HazelcastJsonValue` serializer] includes metadata to allow the cluster to query JSON fields and values. You are charged for this metadata. As a result, the amount of used memory in your cluster may be more than the amount of data that you added to a data structure.

=== Billing Examples

The following examples show the cost of using different resources.

==== Scenario 1: Data Only

You have an empty cluster. You create a map on the cluster, using the default configuration. You then ingest 3 GiB of data into the cluster, run a query, and remove the data. 

For one hour, your cluster stored 3 GiB data, and then the cluster remained empty for the rest of the month.

[cols="a,a,a"]
|===
|Total Storage|Time|Cost

|3 GiB (data) - 2 GiB (free) = 1 GiB
|1 hour
|$0.10

|===

==== Scenario 2: Data and Cluster Backup to Disk

You have two empty clusters managed from the same account. You create maps on both clusters, using the default configuration. You then ingest 3 GiB of data into each cluster. You run the same query on the two clusters, take manual backups, and remove the data from both.

For one hour, each of your clusters stored 3 GiB of data.


[frame=sides,grid=cols,cols="a,a,a,a"]
|===
|Storage Per Cluster|Total Storage|Time|Cost

|*Cluster 1:* 3 GiB (data)
.2+<.^|6 GiB (data) - 2 GiB (free) = 4 GiB
.2+<.^|1 hour
.2+<.^|$0.40

|*Cluster 2:* 3 GiB (data)
|
|
| 

|===

NOTE: The 3 GiB manual backup of each cluster is saved to disk and so is free of charge.

==== Scenario 3: Data and Data Structure Backup

You have two empty clusters managed from the same account. You create maps on both clusters. This time, you update the default map configuration on Cluster 2 to use a backup count of 2. You ingest 3 GiB of data into each cluster. You run the same query on both clusters and remove the data from both. 

For one hour, data was stored on each cluster.

[cols="2a,2a,a,a"]
|===
|Storage Per Cluster|Total Storage|Time|Cost

|*Cluster 1:* 3 GiB (data)
.2+<.^|12 GiB - 5 GiB (free storage + 1x free backup) = 7 GiB
.2+<.^|1 hour
.2+<.^|$0.70

|*Cluster 2:* 3 GiB (data) + 6 GiB (2x backup)
|
|
|

|===

NOTE: As some resources are free of charge, your total resource usage on a cluster dashboard may not match the resources that you are billed for.

== Supported Functionality

Use this table to learn what is supported in {hazelcast-cloud} Serverless clusters:

[cols="1a,1a,1a"]
|===
|Functionality|Production clusters|Development clusters

|xref:create-serverless-cluster.adoc[Create a cluster]
|Supported
|Supported

|xref:deleting-a-cluster.adoc[Delete a cluster]
|Supported
|Supported

|xref:stop-and-resume.adoc[Pause and resume the cluster]
|Supported
|Supported

|xref:connect-to-cluster.adoc[Connect to the cluster]
|Supported
|Supported

|xref:charts-and-stats.adoc[Read metrics]
|Supported
|Supported

|Manually scale the cluster
|Not supported (autoscales)
|Not supported (autoscales)

|Auto scaling
|Supported (always enabled)
|Not supported

|xref:custom-classes-upload.adoc[Custom class upload]
|Supported
|Supported

|xref:map-configurations.adoc[Add data structure configuration]
|Supported
|Supported

|Edit map configuration
|Not Supported
|Not Supported

|Delete data structure configuration
|Not supported
|Not supported

|Automated daily backups
|Supported (always enabled)
|Not supported

|xref:backup-and-restore.adoc[Manual backups]
|Supported
|Not supported

|xref:ip-white-list.adoc[IP whitelisting]
|Supported
|Supported

|xref:management-center.adoc[Management Center]
|Supported
|Supported

|xref:wan-replication.adoc[WAN replication]
|Supported
|Not supported

|Choose a version of Hazelcast member software
|Not supported (always uses the latest version)
|Not supported (always uses the latest version)

|Integrate with an external logging service
|Not supported
|Not supported

|VPC peering
|Not supported
|Not supported

|AWS PrivateLink
|Not supported
|Not supported

|===

== Next Steps

- xref:create-serverless-cluster.adoc[]
