= Serverless Clusters
:description: {hazelcast-cloud} Serverless clusters dynamically scale, depending on the amount of resources you use. Serverless offers a simple pricing model based on storage consumption with the option of creating a cluster for free, without a payment card.
:toc-levels: 3
:page-serverless: true

{description}

== Beta Release

{hazelcast-cloud} Serverless is in beta while we continue to add new features.

Despite its beta state, you can use <<cluster-types, production Serverless clusters>> for production applications.

== Choosing a Cluster Type

// tag::types[]
Serverless clusters come in two types:

- *Development:* Capped storage. You can store at most 1 GiB of data.
- *Production:* Uncapped storage. The cluster scales as you add or remove data.
// end::types[]

[[dev]]
== Development Clusters

// tag::development[]
Development Serverless clusters are for fast, iterative development while you prototype your application.
// end::development[]

Development clusters have the following limitations:

- Maximum 1 GiB of storage
- Only a single member
- No cluster scaling
- No data backups
- No cluster data persistence

When a development cluster restarts for any reason, you lose cluster data such as maps and cluster-side modules.

NOTE: You cannot convert a development cluster to a production cluster.

[[prod]]
== Production Clusters

// tag::production[]
Production Serverless clusters are for applications that have already been tested and are ready to be deployed in real-world scenarios.
// end::production[]

Production Serverless clusters automatically scale up and down, depending on the amount of resources you use.

Your cluster data is persisted on disk so that you can pause and resume your clusters when you want, without losing your data. Cluster data is persisted in the following scenarios:

- Automatic backups once per day.
- When a production cluster restarts for any reason.
- You trigger manual backups.

.What is cluster data?
[%collapsible]
====
include::partial$cluster-data.adoc[]
====

=== Backups

By default, data in production Serverless clusters is backed up on one other Hazelcast member in the cluster.

Although you can configure some xref:data-structures.adoc[data structures] with a custom backup count, the effective backup count is limited by the number of members in your cluster. For example, if you configure a map with 5 backups, but your cluster has only 2 members, you will have one effective backup. You cannot scale up Serverless clusters. If you add enough data to the cluster so that it automatically scales up the number of members, more backups will be added, up to your configured count of 5.

== Pricing for Serverless Clusters

You pay only for what you store in RAM. Any data that is stored on disk or in backups is free of charge. As a result, 'storage' is synonymous with RAM in Serverless clusters.

Serverless clusters are billed monthly only for the amount of used storage. The *first 2 GiB of storage in your account is free*. If you use more than 2 GiB across all your clusters, you are charged $0.10 per hour for every additional GiB of used storage, not including the first 2 GiB.

As well as the data that you add to data structures, you are charged for any additional memory usage, excluding backups. *Backups are free*. Additional memory usage may include the following:

- Indexes that you create
- Stateful jobs
- Serialization overhead

For example, the xref:cluster-side-modules.adoc#serializers[`HazelcastJsonValue` serializer] includes metadata to allow the cluster to query JSON fields and values. You are charged for this metadata. As a result, the amount of used memory in your cluster may be more than the amount of data that you added to a data structure.

=== Restrictions on Free Serverless Clusters

Development and production clusters are stopped when both of these conditions are true:

- You don't connect to the cluster for 24 hours.
- You don't have a payment method set up for your {hazelcast-cloud} account.

If you're using a production Serverless cluster, Hazelcast saves your cluster data so that you can resume the cluster at a later time.

If you're using a development Serverless cluster, all cluster data is lost after the cluster is stopped.

=== Billing Examples

You have an empty cluster. You ingest 3 GiB of data into the cluster, run a query, and remove the data. For one hour, your cluster stored 3 GiB data, and then the cluster remained empty for the rest of the month. You are billed for 1 GiB for one hour, which is $0.10.

These examples show the cost per month of two clusters in the same account:

[cols="a,a,a,a"]
|===
|Cluster|Used storage|Time|Cost

|1
|2 GiB
|Unlimited
|Free

|2
|10 GiB
|10 minutes
|10 GiB * 10/60 * 0.1 = $0.16

|===

== Supported Functionality

Use this table to learn what is supported in Serverless clusters:

[cols="1a,1a,1a"]
|===
|Functionality|Support for production clusters|Support for development clusters

|xref:create-serverless-cluster.adoc[Create a cluster]
|Supported
|Supported

|xref:deleting-a-cluster.adoc[Delete a cluster]
|Supported
|Supported

|xref:stop-and-resume.adoc[Stop and resume the cluster]
|Supported
|Supported

|xref:connect-to-cluster.adoc[Connect to the cluster]
|Supported
|Supported

|xref:charts-and-stats.adoc[Read metrics]
|Supported
|Supported

|Manually scale the cluster
|Not supported (autoscales)
|Not supported (autoscales)

|Auto scaling
|Supported (always enabled)
|Not supported

|xref:custom-classes-upload.adoc[Custom class upload]
|Supported
|Supported

|xref:map-configurations.adoc[Add data structure configuration]
|Supported
|Supported

|Edit map configuration
|Not Supported
|Not Supported

|Delete data structure configuration
|Not supported
|Not supported

|Automated daily backups
|Supported (always enabled)
|Not supported

|xref:backup-and-restore.adoc[Manual backups]
|Supported
|Not supported

|xref:ip-white-list.adoc[IP whitelisting]
|Supported
|Supported

|xref:management-center.adoc[Management Center]
|Supported
|Supported

|xref:wan-replication.adoc[WAN replication]
|Supported
|Not supported

|Choose a version of Hazelcast member software
|Not supported (always uses the latest version)
|Not supported (always uses the latest version)

|Integrate with an external logging service
|Not supported
|Not supported

|VPC peering
|Not supported
|Not supported

|AWS PrivateLink
|Not supported
|Not supported

|===

== Next Steps

- xref:create-serverless-cluster.adoc[]
