= SQL Hello World
:description: Follow this five-minute tutorial to set up a Hazelcast cluster in the cloud. In five minutes, you will learn how to create a cluster, connect to the SQL shell, and use SQL to write data to memory and query that data.

{description}

To run a Hazelcast cluster on your local machine instead, see xref:hazelcast:getting-started:get-started-cli.adoc[].

++++
<script type="application/ld+json">
{
"@context": "http://schema.org",
"@type": "HowTo",
"name": "{hazelcast-cloud} Quickstart",
"description": "Follow this five-minute tutorial to set up a Hazelcast cluster in the cloud. In five minutes, you will learn how to create a cluster, connect to the SQL shell, and use SQL to write data to memory and query that data.",
"totalTime": "PT5M",
"step":[
    {
        "@type": "HowToStep",
        "text": "Create a Cluster."
    },
    {
        "@type": "HowToStep",
        "text": "Download the CLI Client."
    }, {
        "@type": "HowToStep",
        "text": "Connect to the SQL shell."
    }, {
        "@type": "HowToStep",
        "text": "Create a Mapping."
    }, {
        "@type": "HowToStep",
        "text": "Run Queries."
    }]
}
</script>
++++

== Before you Begin

You need a xref:create-account.adoc[{hazelcast-cloud} account].

link:https://docs.npmjs.com/cli/v8/configuring-npm/install[Install the npm package manager].

== Step 1. Start a {hazelcast-cloud} Cluster

In the {hazelcast-cloud} console, do the following:

include::create-serverless-cluster.adoc[tag=development] 

== Step 2. Download the CLI Client

. Open the {hazelcast-cloud} console and click *Connect your Application*.

```sql
CREATE OR REPLACE MAPPING trades (
	id BIGINT,
	ticker VARCHAR,
	price DECIMAL,
	amount BIGINT)
TYPE Kafka
OPTIONS (
  'valueFormat' = 'json-flat',
  -- Required connection configs for Kafka producer, consumer, and admin
  'bootstrap.servers'='pkc-lgk0v.us-west1.gcp.confluent.cloud:9092',
  'security.protocol'='SASL_SSL',
  'sasl.jaas.config'='org.apache.kafka.common.security.plain.PlainLoginModule required username="CTESMTWSRHVANLGI" password="IWk3rK4P7p5J/5OEJR7jbt7lmP2e5txPe9/7qZU751Dxb+uSy3W1zT4KS/kdlyVQ";',
  'sasl.mechanism'='PLAIN',
  --Required for correctness in Apache Kafka clients prior to 2.6
  'client.dns.lookup'='use_all_dns_ips'
);
```

== Next Steps

Build an application with one of our clients:

- xref:java-client.adoc[Java]
- xref:nodejs-client.adoc[Node.js] 
- xref:net-client.adoc[.NET]
- xref:python-client.adoc[Python]
- xref:go-client.adoc[Go]

Find out more about the statements used in this tutorial:

- xref:hazelcast:sql:create-mapping.adoc[]
- xref:hazelcast:sql:select.adoc[]
- xref:hazelcast:sql:expressions.adoc[].

Explore xref:hazelcast:sql:sql-statements.adoc[all available SQL statements].
