= Stopping and Resuming Clusters
:description: Stopping a cluster saves your cluster's configuration and stops charges accumulating in your account.
:page-aliases: manage-the-cluster.adoc

{description}

To stop clusters in a team, you must have either an admin or developer role. See xref:teams-and-users.adoc[].

You cannot stop a Dedicated cluster if it's hosted on Google Cloud Platform (GCP).

== Stopping a Cluster

Stopping your cluster can help minimize your costs during development because you are only charged for running clusters.

. Sign into the [.console]*link:{page-cloud-console}[{hazelcast-cloud} console]* and select your cluster.
. Click *Stop*.

If you're using a production Serverless cluster or a Dedicated cluster, {hazelcast-cloud} saves your cluster data so that you can resume the cluster at a later time.

.What is cluster data?
[%collapsible]
====
include::partial$cluster-data.adoc[]
====

If you're using a development Serverless cluster, all cluster data is lost after the cluster is stopped.

== Resuming a Cluster

. Sign into the [.console]*link:{page-cloud-console}[{hazelcast-cloud} console]* and select your cluster.
. Click *Resume*.
