= Support
:url-zendesk-hazelcast: https://hazelcast.zendesk.com/

Hazelcast Cloud has different support options depending on your requirements. Here are the support levels:

== Standard

Standard support is available for all users with non-free clusters.

*Coverage:* 24 hours a day, 7 days a week, 365 days a year

*Support Channel:* link:{url-zendesk-hazelcast}[ZenDesk]

*Our Response Times:*

We will respond in less than one business day.

== Enterprise

If you're interested in Enterprise support, contact us at mailto:sales@hazelcast.com[].

*Coverage:* 24 hours a day, 7 days a week, 365 days a year

*Support Channels:* link:{url-zendesk-hazelcast}[ZenDesk], Emergency Telephone Number

*Our Response Times:*

Severity 1 (production applications are down): We will respond in less than 30 minutes.

Severity 2 (a major incident with significant impact): First Response < 2 Hours

Severity 3 (a minor incident with low impact): First Response < 4 Hours

Severity 4 (an insignificant issue with little to no impact): First Response < 1 Business Day

== Contact Us

Have a question? Need some information? Email us: mailto:support@hazelcast.com[]
