= Support
:url-zendesk-hazelcast: https://hazelcast.zendesk.com/

Hazelcast Cloud has different support options depending on your requirements. Here are the support levels:

== Standard Support

Standard support is available for all users with Standard or Enterprise clusters.

*Coverage:* 24 hours a day, 7 days a week, 365 days a year

*Support Channel:* link:{url-zendesk-hazelcast}[ZenDesk]

*Our Response Times:*

We will respond in less than one business day.

== Enterprise Support

If you're interested in Enterprise support, contact us at mailto:sales@hazelcast.com[].

*Coverage:* 24 hours a day, 7 days a week, 365 days a year

*Support Channels:* link:{url-zendesk-hazelcast}[ZenDesk], Emergency Telephone Number

*Our Response Times:*

Severity 1 (production applications are down): We will respond in less than 30 minutes.

Severity 2 (production applications are down and there is a known workaround): We will respond in less than 2 hours.

Severity 3 (low impact on applications): We will respond in less than 4 hours.

Severity 4 (insignificant issue with little to no impact): We will respond in less than one business day.

== Contact Us

Have a question? Need some information? Email us: mailto:support@hazelcast.com[]
