= Teams and User Roles
:description: To collaborate with other team members, you can allow them to access specific clusters by inviting them to a team and assigning them roles based on what actions they need to perform on the team's clusters.

{description}

== Creating a Team

. Click the *Account* icon in the bottom left corner.

. Enter a team name and click *Create Team*.

Now that you've created a team, you can invite users to it and assign them roles.

== Inviting Users to a Team

If you've created one or more teams, you can invite users to them and assign those users a role.

. Select an existing team from the dropdown.

. Enter the email address of the team member that you want to add and assign them a role from the dropdown.

. Click *Invite*.

The user will receive an email invitation. When the user accepts the invitation, the user's status will change to *Active*.

== Viewing your Team's Clusters

To see the teams that you are in and the role that you have in that team, click the *Account* icon in the bottom left corner and use the dropdown next to your name.

Select a team to see only clusters that are owned by that team.

[[roles]]
== Team Roles

In each team, users can have one of the following roles:

[cols="2a,1a,1a,1a,1a"]
|===
|Roles ->|Admin|Developer|Finance|View only

|Creating new clusters for the team
|yes
|yes
|no
|no

|Managing billing settings and redeeming credits
|yes
|no
|yes
|no

|Managing API keys
|yes
|yes
|no
|no

|Updating cluster settings
|yes
|yes
|no
|no

|Viewing charts and metrics
|yes
|yes
|yes
|yes

|===