= Developer Tools
:description: Hazelcast provides a variety of developer tools for creating, testing and debugging applications.
:cloud-tags: Develop Applications
:cloud-order: 24

{description}

== Client Libraries

You can use any available client library to connect to Hazelcast {hazelcast-cloud} clusters.

See link:https://hazelcast.com/clients/[Clients and Languages].

== Hazelcast {hazelcast-cloud} CLI

Hazelcast {hazelcast-cloud} CLI is a command-line tool for creating and managing {hazelcast-cloud} clusters.

See the documentation on link:{page-url-github-cloud-cli}[GitHub].

== Maven Plugin for {hazelcast-cloud} Serverless
[.beta]*Beta*

The Maven plugin for {hazelcast-cloud} Serverless is a Java development tool for testing and deploying cluster-side modules on {hazelcast-cloud} Serverless clusters.

See xref:maven-plugin-hazelcast.adoc[].

== Hazelcast CLC

Hazelcast Command-Line Client (CLC) is a command-line tool for connecting to and monitoring local and remote {hazelcast-cloud} Serverless clusters. The Hazelcast CLC also allows you to create and manage data pipelines and data structures on your clusters, and to query cluster data using SQL.

See xref:clc:ROOT:overview.adoc[the documentation] for example use cases, tutorials, installation instructions, configuration details, and a full list of commands.

