= Developer Tools
:description: Hazelcast provides a variety of developer tools for creating, testing and debugging applications.

{description}

== Client Libraries

You can use any available client library to connect to Hazelcast {hazelcast-cloud} clusters.

See link:https://hazelcast.com/clients/[Clients and Languages].

== Maven Plugin for Hazelcast {hazelcast-cloud}
[.serverless]*Serverless*

The Maven plugin for Hazelcast {hazelcast-cloud} is a Java development tool for testing and deploying cluster-side modules for Hazelcast Serverless.

See xref:maven-plugin-hazelcast.adoc[].

== Hazelcast {hazelcast-cloud} CLI

Hazelcast {hazelcast-cloud} CLI is a command-line tool for creating and managing {hazelcast-cloud} clusters.

See the documentation on link:{page-url-github-cloud-cli}[GitHub].

== Hazelcast CLC

Hazelcast Command-Line Client (CLC) is a command-line tool for connecting to {hazelcast-cloud} clusters, creating and managing data structures, and monitoring clusters.

See the documentation on link:https://github.com/hazelcast/hazelcast-commandline-client[GitHub].

== Hazelcast {hazelcast-cloud} Go SDK

Hazelcast {hazelcast-cloud} Go SDK is a Go library for creating and managing {hazelcast-cloud} clusters.

See the documentation on link:{page-url-github-go-sdk}[GitHub].

== GraphQL API

Hazelcast {hazelcast-cloud} uses GraphQL to provide a public API to consumers such as the Hazelcast {hazelcast-cloud} Go SDK.

See xref:api-reference.adoc[].
