= Topic

Hazelcast provides a distribution mechanism for publishing messages that are delivered to multiple subscribers. This is also known as a publish/subscribe (pub/sub) messaging model. Publishing and subscribing operations are cluster-wide. When a member subscribes to a topic, it is actually registering for messages published by any member in the cluster, including the new members that joined after you add the listener.

== Topic Name

In Hazelcast, you can create custom topic configurations associated with the names of the topic. The topic that does not have any configuration defined use the default configuration. If you want to set a configuration that is valid for all topics, you can name your configuration as `default`. A user-defined `default` configuration applies to every topic that does not have a specific custom topic configuration defined with the topic's name. 
You can also use wildcards to associate your configuration with multiple topic names. See the xref:hazelcast:configuration:using-wildcards.adoc[configuration documentation] for more information about wildcards.

== Global Ordering

Global ordering enables all receivers to receive all messages from all sources with the same order.

NOTE: The default value is false.
