= Synchronizing Data Between Clusters
:description: You can use WAN replication to synchronize data between two or more clusters, and to transfer data from one cluster to another.

{description}

== Use Cases

WAN replication supports the following use cases:

* Use WAN replication with a xref:failover-clients-with-hazelcast-cloud.adoc[failover client] as part of your disaster recovery strategy. WAN replication automatically synchronizes data between clusters. If a cluster fails, the failover client can switch to an alternative cluster with minimal disruption to service.

* Migrate data to a new cluster before decommissioning your original cluster.



== Terminology

[cols="a,a"]
|===
|Term|Description

| _Publisher_ cluster, also known as the _active_ cluster
|Sends or transfers data to another cluster using WAN replication

| _Consumer_ cluster, also known as the _passive_ cluster
|Receives data from another cluster using WAN replication

|_Active-Passive_ replication
|One-way replication. Data updates on a publisher cluster are automatically copied to a consumer cluster. Use this configuration for migrating data between clusters.

|_Active-Active_ replication
|Uses a pair of publisher clusters for two-way replication. Data updates on either cluster are automatically copied to the other cluster of the pair. Use this configuration with a failover client.

|===

== Before you Begin

* You need two xref:create-serverless-cluster.adoc[Serverless clusters] or two xref:create-dedicated-cluster.adoc[Dedicated clusters]. You cannot synchronize data between one Serverless cluster and one Dedicated cluster.

+
Make sure that each cluster is configured with the same settings. For example, if one cluster
contains xref:cluster-side-modules.adoc[cluster-side modules] or persistence, the other cluster must too.

* Decide which configuration to use for your pair of clusters:
** Active-Passive
** Active-Active

== Set Up WAN Replication

Set up WAN replication between two clusters.

. Sign into the [.console]*link:{page-cloud-console}[{hazelcast-cloud} console]* and select the cluster that you want to use as a publisher cluster.

+
NOTE: If you want to set up a pair of clusters in an Active-Active configuration, select either cluster.

. Select *Manage Cluster* > *Settings*.
. On the *Cluster Settings* page, select *WAN Replication* and then click *+ Create New Replication*.

+
The cluster is set as the *Active* cluster. Any data updates performed on this cluster are automatically copied to the other cluster of the pair.

. Either leave the default options for the following parameters, or update them to suit your use case.

* *Queue Full Behavior*: Lets you decide what to do when the replication events queue is full. 

** `THROW AN EXCEPTION`: Throws a `WanReplicationQueueFullException` when the queue is full. Processing of replication events stops until action is taken.
** `THROW AN EXCEPTION ONLY IF REPLICATION ACTIVE`: As above, but this option is only triggered when both clusters connected by WAN replication are active.
** `NONE`: Discards replication events when the queue is full. This option is only suitable for non-critical data. 

* *Queue Capacity*: Sets the maximum size for the replication events queue. When this limit is reached, the *Queue Full Behavior* is triggered.
* *Batch Size*: Sets the maximum size of replication events that are sent in a single batch.
* *Batch Max Delay Millis*: By default, all replication events are delayed by one second (1000 milliseconds) before they are sent to the other cluster of the pair, unless they exceed the *Batch Size*.

. Click *Next >* to configure the other cluster of the pair.
. From the *Active/Passive* list, select the correct behavior for your second cluster: 

* *Passive*: Receives only data updates.
* *Active*: Sends and receives data updates. 

. Click *Save*. WAN Replication is set up.

+
TIP: If you want to synchronize all data between the two clusters immediately, click *Sync*. This option is useful when your're migrating data from one cluster to another. Otherwise, WAN replication is triggered when a data update is made to a publisher cluster.

== Verify WAN Replication

Check that data is successfully replicated between two clusters connected by WAN replication.

. Connect a client to your publisher cluster and write some data to a map. You can use either cluster in an Active-Active pair.
. Open the dashboard of the other cluster of the pair and select *Manage Cluster* > *Management Center*.
. Go to *Storage* > *Maps* and make sure that the new map entries have been written to this cluster. Or if you've written or synched other data types, check the relevant section of Management Center.

+
TIP: You can also check the status of WAN replication from Management Center for your publisher cluster. Go to *Cluster* > *WAN Replication*.

== Delete a Cluster Using WAN Replication

Learn how to delete a cluster that has WAN replication set up. 

Before you start, check that all the data you need has been replicated to another cluster.

To delete a consumer cluster:

. Identify the connected publisher cluster. From the dashboard of the consumer cluster, go to *Manage Cluster* > *Settings*. On the *Cluster Settings* page, select *WAN Replication* and look for the ID of publisher cluster.
. Open the dashboard of the publisher cluster.
. Go to *Manage Cluster* > *Settings*. 
. Remove WAN replication. On the *Cluster Settings* page, select *WAN Replication* and then click *Delete*. Confirm your deletion.
. Return to the dashboard of the consumer cluster and delete the cluster.

To delete a publisher cluster:

. Follow steps 2 to 4 as for the consumer cluster.
. Go to the dashboard of your publisher cluster and delete the cluster.

